package com.sforce.soap.tooling.sobject;

/**
 * This is a generated class for the SObject Enterprise API.
 * Do not edit this file, as your changes will be lost.
 */
public class ApexTestRunResult extends com.sforce.soap.tooling.sobject.SObject {

    /**
     * Constructor
     */
    public ApexTestRunResult() {}

    /* Cache the typeInfo instead of declaring static fields throughout*/
    private transient java.util.Map<String, com.sforce.ws.bind.TypeInfo> typeInfoCache = new java.util.HashMap<String, com.sforce.ws.bind.TypeInfo>();
    private com.sforce.ws.bind.TypeInfo _lookupTypeInfo(String fieldName, String namespace, String name, String typeNS, String type, int minOcc, int maxOcc, boolean elementForm) {
      com.sforce.ws.bind.TypeInfo typeInfo = typeInfoCache.get(fieldName);
      if (typeInfo == null) {
        typeInfo = new com.sforce.ws.bind.TypeInfo(namespace, name, typeNS, type, minOcc, maxOcc, elementForm);
        typeInfoCache.put(fieldName, typeInfo);
      }
      return typeInfo;
    }

    /**
     * element : AsyncApexJob of type {urn:sobject.tooling.soap.sforce.com}AsyncApexJob
     * java type: com.sforce.soap.tooling.sobject.AsyncApexJob
     */
    private boolean AsyncApexJob__is_set = false;

    private com.sforce.soap.tooling.sobject.AsyncApexJob AsyncApexJob;

    public com.sforce.soap.tooling.sobject.AsyncApexJob getAsyncApexJob() {
      return AsyncApexJob;
    }

    public void setAsyncApexJob(com.sforce.soap.tooling.sobject.AsyncApexJob AsyncApexJob) {
      this.AsyncApexJob = AsyncApexJob;
      AsyncApexJob__is_set = true;
    }

    protected void setAsyncApexJob(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("AsyncApexJob", "urn:sobject.tooling.soap.sforce.com","AsyncApexJob","urn:sobject.tooling.soap.sforce.com","AsyncApexJob",0,1,true))) {
        setAsyncApexJob((com.sforce.soap.tooling.sobject.AsyncApexJob)__typeMapper.readObject(__in, _lookupTypeInfo("AsyncApexJob", "urn:sobject.tooling.soap.sforce.com","AsyncApexJob","urn:sobject.tooling.soap.sforce.com","AsyncApexJob",0,1,true), com.sforce.soap.tooling.sobject.AsyncApexJob.class));
      }
    }

    private void writeFieldAsyncApexJob(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("AsyncApexJob", "urn:sobject.tooling.soap.sforce.com","AsyncApexJob","urn:sobject.tooling.soap.sforce.com","AsyncApexJob",0,1,true), AsyncApexJob, AsyncApexJob__is_set);
    }

    /**
     * element : AsyncApexJobId of type {urn:tooling.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private boolean AsyncApexJobId__is_set = false;

    private java.lang.String AsyncApexJobId;

    public java.lang.String getAsyncApexJobId() {
      return AsyncApexJobId;
    }

    public void setAsyncApexJobId(java.lang.String AsyncApexJobId) {
      this.AsyncApexJobId = AsyncApexJobId;
      AsyncApexJobId__is_set = true;
    }

    protected void setAsyncApexJobId(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("AsyncApexJobId", "urn:sobject.tooling.soap.sforce.com","AsyncApexJobId","urn:tooling.soap.sforce.com","ID",0,1,true))) {
        setAsyncApexJobId(__typeMapper.readString(__in, _lookupTypeInfo("AsyncApexJobId", "urn:sobject.tooling.soap.sforce.com","AsyncApexJobId","urn:tooling.soap.sforce.com","ID",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldAsyncApexJobId(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("AsyncApexJobId", "urn:sobject.tooling.soap.sforce.com","AsyncApexJobId","urn:tooling.soap.sforce.com","ID",0,1,true), AsyncApexJobId, AsyncApexJobId__is_set);
    }

    /**
     * element : ClassesCompleted of type {http://www.w3.org/2001/XMLSchema}int
     * java type: java.lang.Integer
     */
    private boolean ClassesCompleted__is_set = false;

    private java.lang.Integer ClassesCompleted;

    public java.lang.Integer getClassesCompleted() {
      return ClassesCompleted;
    }

    public void setClassesCompleted(java.lang.Integer ClassesCompleted) {
      this.ClassesCompleted = ClassesCompleted;
      ClassesCompleted__is_set = true;
    }

    protected void setClassesCompleted(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("ClassesCompleted", "urn:sobject.tooling.soap.sforce.com","ClassesCompleted","http://www.w3.org/2001/XMLSchema","int",0,1,true))) {
        setClassesCompleted((java.lang.Integer)__typeMapper.readObject(__in, _lookupTypeInfo("ClassesCompleted", "urn:sobject.tooling.soap.sforce.com","ClassesCompleted","http://www.w3.org/2001/XMLSchema","int",0,1,true), java.lang.Integer.class));
      }
    }

    private void writeFieldClassesCompleted(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("ClassesCompleted", "urn:sobject.tooling.soap.sforce.com","ClassesCompleted","http://www.w3.org/2001/XMLSchema","int",0,1,true), ClassesCompleted, ClassesCompleted__is_set);
    }

    /**
     * element : ClassesEnqueued of type {http://www.w3.org/2001/XMLSchema}int
     * java type: java.lang.Integer
     */
    private boolean ClassesEnqueued__is_set = false;

    private java.lang.Integer ClassesEnqueued;

    public java.lang.Integer getClassesEnqueued() {
      return ClassesEnqueued;
    }

    public void setClassesEnqueued(java.lang.Integer ClassesEnqueued) {
      this.ClassesEnqueued = ClassesEnqueued;
      ClassesEnqueued__is_set = true;
    }

    protected void setClassesEnqueued(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("ClassesEnqueued", "urn:sobject.tooling.soap.sforce.com","ClassesEnqueued","http://www.w3.org/2001/XMLSchema","int",0,1,true))) {
        setClassesEnqueued((java.lang.Integer)__typeMapper.readObject(__in, _lookupTypeInfo("ClassesEnqueued", "urn:sobject.tooling.soap.sforce.com","ClassesEnqueued","http://www.w3.org/2001/XMLSchema","int",0,1,true), java.lang.Integer.class));
      }
    }

    private void writeFieldClassesEnqueued(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("ClassesEnqueued", "urn:sobject.tooling.soap.sforce.com","ClassesEnqueued","http://www.w3.org/2001/XMLSchema","int",0,1,true), ClassesEnqueued, ClassesEnqueued__is_set);
    }

    /**
     * element : CreatedBy of type {urn:sobject.tooling.soap.sforce.com}User
     * java type: com.sforce.soap.tooling.sobject.User
     */
    private boolean CreatedBy__is_set = false;

    private com.sforce.soap.tooling.sobject.User CreatedBy;

    public com.sforce.soap.tooling.sobject.User getCreatedBy() {
      return CreatedBy;
    }

    public void setCreatedBy(com.sforce.soap.tooling.sobject.User CreatedBy) {
      this.CreatedBy = CreatedBy;
      CreatedBy__is_set = true;
    }

    protected void setCreatedBy(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("CreatedBy", "urn:sobject.tooling.soap.sforce.com","CreatedBy","urn:sobject.tooling.soap.sforce.com","User",0,1,true))) {
        setCreatedBy((com.sforce.soap.tooling.sobject.User)__typeMapper.readObject(__in, _lookupTypeInfo("CreatedBy", "urn:sobject.tooling.soap.sforce.com","CreatedBy","urn:sobject.tooling.soap.sforce.com","User",0,1,true), com.sforce.soap.tooling.sobject.User.class));
      }
    }

    private void writeFieldCreatedBy(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("CreatedBy", "urn:sobject.tooling.soap.sforce.com","CreatedBy","urn:sobject.tooling.soap.sforce.com","User",0,1,true), CreatedBy, CreatedBy__is_set);
    }

    /**
     * element : CreatedById of type {urn:tooling.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private boolean CreatedById__is_set = false;

    private java.lang.String CreatedById;

    public java.lang.String getCreatedById() {
      return CreatedById;
    }

    public void setCreatedById(java.lang.String CreatedById) {
      this.CreatedById = CreatedById;
      CreatedById__is_set = true;
    }

    protected void setCreatedById(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("CreatedById", "urn:sobject.tooling.soap.sforce.com","CreatedById","urn:tooling.soap.sforce.com","ID",0,1,true))) {
        setCreatedById(__typeMapper.readString(__in, _lookupTypeInfo("CreatedById", "urn:sobject.tooling.soap.sforce.com","CreatedById","urn:tooling.soap.sforce.com","ID",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldCreatedById(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("CreatedById", "urn:sobject.tooling.soap.sforce.com","CreatedById","urn:tooling.soap.sforce.com","ID",0,1,true), CreatedById, CreatedById__is_set);
    }

    /**
     * element : CreatedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private boolean CreatedDate__is_set = false;

    private java.util.Calendar CreatedDate;

    public java.util.Calendar getCreatedDate() {
      return CreatedDate;
    }

    public void setCreatedDate(java.util.Calendar CreatedDate) {
      this.CreatedDate = CreatedDate;
      CreatedDate__is_set = true;
    }

    protected void setCreatedDate(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("CreatedDate", "urn:sobject.tooling.soap.sforce.com","CreatedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true))) {
        setCreatedDate((java.util.Calendar)__typeMapper.readObject(__in, _lookupTypeInfo("CreatedDate", "urn:sobject.tooling.soap.sforce.com","CreatedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), java.util.Calendar.class));
      }
    }

    private void writeFieldCreatedDate(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("CreatedDate", "urn:sobject.tooling.soap.sforce.com","CreatedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), CreatedDate, CreatedDate__is_set);
    }

    /**
     * element : EndTime of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private boolean EndTime__is_set = false;

    private java.util.Calendar EndTime;

    public java.util.Calendar getEndTime() {
      return EndTime;
    }

    public void setEndTime(java.util.Calendar EndTime) {
      this.EndTime = EndTime;
      EndTime__is_set = true;
    }

    protected void setEndTime(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("EndTime", "urn:sobject.tooling.soap.sforce.com","EndTime","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true))) {
        setEndTime((java.util.Calendar)__typeMapper.readObject(__in, _lookupTypeInfo("EndTime", "urn:sobject.tooling.soap.sforce.com","EndTime","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), java.util.Calendar.class));
      }
    }

    private void writeFieldEndTime(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("EndTime", "urn:sobject.tooling.soap.sforce.com","EndTime","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), EndTime, EndTime__is_set);
    }

    /**
     * element : IsAllTests of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private boolean IsAllTests__is_set = false;

    private java.lang.Boolean IsAllTests;

    public java.lang.Boolean getIsAllTests() {
      return IsAllTests;
    }

    public void setIsAllTests(java.lang.Boolean IsAllTests) {
      this.IsAllTests = IsAllTests;
      IsAllTests__is_set = true;
    }

    protected void setIsAllTests(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("IsAllTests", "urn:sobject.tooling.soap.sforce.com","IsAllTests","http://www.w3.org/2001/XMLSchema","boolean",0,1,true))) {
        setIsAllTests((java.lang.Boolean)__typeMapper.readObject(__in, _lookupTypeInfo("IsAllTests", "urn:sobject.tooling.soap.sforce.com","IsAllTests","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), java.lang.Boolean.class));
      }
    }

    private void writeFieldIsAllTests(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("IsAllTests", "urn:sobject.tooling.soap.sforce.com","IsAllTests","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), IsAllTests, IsAllTests__is_set);
    }

    /**
     * element : IsDeleted of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private boolean IsDeleted__is_set = false;

    private java.lang.Boolean IsDeleted;

    public java.lang.Boolean getIsDeleted() {
      return IsDeleted;
    }

    public void setIsDeleted(java.lang.Boolean IsDeleted) {
      this.IsDeleted = IsDeleted;
      IsDeleted__is_set = true;
    }

    protected void setIsDeleted(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("IsDeleted", "urn:sobject.tooling.soap.sforce.com","IsDeleted","http://www.w3.org/2001/XMLSchema","boolean",0,1,true))) {
        setIsDeleted((java.lang.Boolean)__typeMapper.readObject(__in, _lookupTypeInfo("IsDeleted", "urn:sobject.tooling.soap.sforce.com","IsDeleted","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), java.lang.Boolean.class));
      }
    }

    private void writeFieldIsDeleted(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("IsDeleted", "urn:sobject.tooling.soap.sforce.com","IsDeleted","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), IsDeleted, IsDeleted__is_set);
    }

    /**
     * element : JobName of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean JobName__is_set = false;

    private java.lang.String JobName;

    public java.lang.String getJobName() {
      return JobName;
    }

    public void setJobName(java.lang.String JobName) {
      this.JobName = JobName;
      JobName__is_set = true;
    }

    protected void setJobName(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("JobName", "urn:sobject.tooling.soap.sforce.com","JobName","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setJobName(__typeMapper.readString(__in, _lookupTypeInfo("JobName", "urn:sobject.tooling.soap.sforce.com","JobName","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldJobName(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("JobName", "urn:sobject.tooling.soap.sforce.com","JobName","http://www.w3.org/2001/XMLSchema","string",0,1,true), JobName, JobName__is_set);
    }

    /**
     * element : LastModifiedBy of type {urn:sobject.tooling.soap.sforce.com}User
     * java type: com.sforce.soap.tooling.sobject.User
     */
    private boolean LastModifiedBy__is_set = false;

    private com.sforce.soap.tooling.sobject.User LastModifiedBy;

    public com.sforce.soap.tooling.sobject.User getLastModifiedBy() {
      return LastModifiedBy;
    }

    public void setLastModifiedBy(com.sforce.soap.tooling.sobject.User LastModifiedBy) {
      this.LastModifiedBy = LastModifiedBy;
      LastModifiedBy__is_set = true;
    }

    protected void setLastModifiedBy(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("LastModifiedBy", "urn:sobject.tooling.soap.sforce.com","LastModifiedBy","urn:sobject.tooling.soap.sforce.com","User",0,1,true))) {
        setLastModifiedBy((com.sforce.soap.tooling.sobject.User)__typeMapper.readObject(__in, _lookupTypeInfo("LastModifiedBy", "urn:sobject.tooling.soap.sforce.com","LastModifiedBy","urn:sobject.tooling.soap.sforce.com","User",0,1,true), com.sforce.soap.tooling.sobject.User.class));
      }
    }

    private void writeFieldLastModifiedBy(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("LastModifiedBy", "urn:sobject.tooling.soap.sforce.com","LastModifiedBy","urn:sobject.tooling.soap.sforce.com","User",0,1,true), LastModifiedBy, LastModifiedBy__is_set);
    }

    /**
     * element : LastModifiedById of type {urn:tooling.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private boolean LastModifiedById__is_set = false;

    private java.lang.String LastModifiedById;

    public java.lang.String getLastModifiedById() {
      return LastModifiedById;
    }

    public void setLastModifiedById(java.lang.String LastModifiedById) {
      this.LastModifiedById = LastModifiedById;
      LastModifiedById__is_set = true;
    }

    protected void setLastModifiedById(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("LastModifiedById", "urn:sobject.tooling.soap.sforce.com","LastModifiedById","urn:tooling.soap.sforce.com","ID",0,1,true))) {
        setLastModifiedById(__typeMapper.readString(__in, _lookupTypeInfo("LastModifiedById", "urn:sobject.tooling.soap.sforce.com","LastModifiedById","urn:tooling.soap.sforce.com","ID",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldLastModifiedById(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("LastModifiedById", "urn:sobject.tooling.soap.sforce.com","LastModifiedById","urn:tooling.soap.sforce.com","ID",0,1,true), LastModifiedById, LastModifiedById__is_set);
    }

    /**
     * element : LastModifiedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private boolean LastModifiedDate__is_set = false;

    private java.util.Calendar LastModifiedDate;

    public java.util.Calendar getLastModifiedDate() {
      return LastModifiedDate;
    }

    public void setLastModifiedDate(java.util.Calendar LastModifiedDate) {
      this.LastModifiedDate = LastModifiedDate;
      LastModifiedDate__is_set = true;
    }

    protected void setLastModifiedDate(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("LastModifiedDate", "urn:sobject.tooling.soap.sforce.com","LastModifiedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true))) {
        setLastModifiedDate((java.util.Calendar)__typeMapper.readObject(__in, _lookupTypeInfo("LastModifiedDate", "urn:sobject.tooling.soap.sforce.com","LastModifiedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), java.util.Calendar.class));
      }
    }

    private void writeFieldLastModifiedDate(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("LastModifiedDate", "urn:sobject.tooling.soap.sforce.com","LastModifiedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), LastModifiedDate, LastModifiedDate__is_set);
    }

    /**
     * element : MethodsCompleted of type {http://www.w3.org/2001/XMLSchema}int
     * java type: java.lang.Integer
     */
    private boolean MethodsCompleted__is_set = false;

    private java.lang.Integer MethodsCompleted;

    public java.lang.Integer getMethodsCompleted() {
      return MethodsCompleted;
    }

    public void setMethodsCompleted(java.lang.Integer MethodsCompleted) {
      this.MethodsCompleted = MethodsCompleted;
      MethodsCompleted__is_set = true;
    }

    protected void setMethodsCompleted(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("MethodsCompleted", "urn:sobject.tooling.soap.sforce.com","MethodsCompleted","http://www.w3.org/2001/XMLSchema","int",0,1,true))) {
        setMethodsCompleted((java.lang.Integer)__typeMapper.readObject(__in, _lookupTypeInfo("MethodsCompleted", "urn:sobject.tooling.soap.sforce.com","MethodsCompleted","http://www.w3.org/2001/XMLSchema","int",0,1,true), java.lang.Integer.class));
      }
    }

    private void writeFieldMethodsCompleted(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("MethodsCompleted", "urn:sobject.tooling.soap.sforce.com","MethodsCompleted","http://www.w3.org/2001/XMLSchema","int",0,1,true), MethodsCompleted, MethodsCompleted__is_set);
    }

    /**
     * element : MethodsEnqueued of type {http://www.w3.org/2001/XMLSchema}int
     * java type: java.lang.Integer
     */
    private boolean MethodsEnqueued__is_set = false;

    private java.lang.Integer MethodsEnqueued;

    public java.lang.Integer getMethodsEnqueued() {
      return MethodsEnqueued;
    }

    public void setMethodsEnqueued(java.lang.Integer MethodsEnqueued) {
      this.MethodsEnqueued = MethodsEnqueued;
      MethodsEnqueued__is_set = true;
    }

    protected void setMethodsEnqueued(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("MethodsEnqueued", "urn:sobject.tooling.soap.sforce.com","MethodsEnqueued","http://www.w3.org/2001/XMLSchema","int",0,1,true))) {
        setMethodsEnqueued((java.lang.Integer)__typeMapper.readObject(__in, _lookupTypeInfo("MethodsEnqueued", "urn:sobject.tooling.soap.sforce.com","MethodsEnqueued","http://www.w3.org/2001/XMLSchema","int",0,1,true), java.lang.Integer.class));
      }
    }

    private void writeFieldMethodsEnqueued(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("MethodsEnqueued", "urn:sobject.tooling.soap.sforce.com","MethodsEnqueued","http://www.w3.org/2001/XMLSchema","int",0,1,true), MethodsEnqueued, MethodsEnqueued__is_set);
    }

    /**
     * element : MethodsFailed of type {http://www.w3.org/2001/XMLSchema}int
     * java type: java.lang.Integer
     */
    private boolean MethodsFailed__is_set = false;

    private java.lang.Integer MethodsFailed;

    public java.lang.Integer getMethodsFailed() {
      return MethodsFailed;
    }

    public void setMethodsFailed(java.lang.Integer MethodsFailed) {
      this.MethodsFailed = MethodsFailed;
      MethodsFailed__is_set = true;
    }

    protected void setMethodsFailed(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("MethodsFailed", "urn:sobject.tooling.soap.sforce.com","MethodsFailed","http://www.w3.org/2001/XMLSchema","int",0,1,true))) {
        setMethodsFailed((java.lang.Integer)__typeMapper.readObject(__in, _lookupTypeInfo("MethodsFailed", "urn:sobject.tooling.soap.sforce.com","MethodsFailed","http://www.w3.org/2001/XMLSchema","int",0,1,true), java.lang.Integer.class));
      }
    }

    private void writeFieldMethodsFailed(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("MethodsFailed", "urn:sobject.tooling.soap.sforce.com","MethodsFailed","http://www.w3.org/2001/XMLSchema","int",0,1,true), MethodsFailed, MethodsFailed__is_set);
    }

    /**
     * element : Source of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean Source__is_set = false;

    private java.lang.String Source;

    public java.lang.String getSource() {
      return Source;
    }

    public void setSource(java.lang.String Source) {
      this.Source = Source;
      Source__is_set = true;
    }

    protected void setSource(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("Source", "urn:sobject.tooling.soap.sforce.com","Source","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setSource(__typeMapper.readString(__in, _lookupTypeInfo("Source", "urn:sobject.tooling.soap.sforce.com","Source","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldSource(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("Source", "urn:sobject.tooling.soap.sforce.com","Source","http://www.w3.org/2001/XMLSchema","string",0,1,true), Source, Source__is_set);
    }

    /**
     * element : StartTime of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private boolean StartTime__is_set = false;

    private java.util.Calendar StartTime;

    public java.util.Calendar getStartTime() {
      return StartTime;
    }

    public void setStartTime(java.util.Calendar StartTime) {
      this.StartTime = StartTime;
      StartTime__is_set = true;
    }

    protected void setStartTime(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("StartTime", "urn:sobject.tooling.soap.sforce.com","StartTime","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true))) {
        setStartTime((java.util.Calendar)__typeMapper.readObject(__in, _lookupTypeInfo("StartTime", "urn:sobject.tooling.soap.sforce.com","StartTime","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), java.util.Calendar.class));
      }
    }

    private void writeFieldStartTime(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("StartTime", "urn:sobject.tooling.soap.sforce.com","StartTime","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), StartTime, StartTime__is_set);
    }

    /**
     * element : Status of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean Status__is_set = false;

    private java.lang.String Status;

    public java.lang.String getStatus() {
      return Status;
    }

    public void setStatus(java.lang.String Status) {
      this.Status = Status;
      Status__is_set = true;
    }

    protected void setStatus(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("Status", "urn:sobject.tooling.soap.sforce.com","Status","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setStatus(__typeMapper.readString(__in, _lookupTypeInfo("Status", "urn:sobject.tooling.soap.sforce.com","Status","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldStatus(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("Status", "urn:sobject.tooling.soap.sforce.com","Status","http://www.w3.org/2001/XMLSchema","string",0,1,true), Status, Status__is_set);
    }

    /**
     * element : SystemModstamp of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private boolean SystemModstamp__is_set = false;

    private java.util.Calendar SystemModstamp;

    public java.util.Calendar getSystemModstamp() {
      return SystemModstamp;
    }

    public void setSystemModstamp(java.util.Calendar SystemModstamp) {
      this.SystemModstamp = SystemModstamp;
      SystemModstamp__is_set = true;
    }

    protected void setSystemModstamp(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("SystemModstamp", "urn:sobject.tooling.soap.sforce.com","SystemModstamp","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true))) {
        setSystemModstamp((java.util.Calendar)__typeMapper.readObject(__in, _lookupTypeInfo("SystemModstamp", "urn:sobject.tooling.soap.sforce.com","SystemModstamp","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), java.util.Calendar.class));
      }
    }

    private void writeFieldSystemModstamp(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("SystemModstamp", "urn:sobject.tooling.soap.sforce.com","SystemModstamp","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), SystemModstamp, SystemModstamp__is_set);
    }

    /**
     * element : TestTime of type {http://www.w3.org/2001/XMLSchema}int
     * java type: java.lang.Integer
     */
    private boolean TestTime__is_set = false;

    private java.lang.Integer TestTime;

    public java.lang.Integer getTestTime() {
      return TestTime;
    }

    public void setTestTime(java.lang.Integer TestTime) {
      this.TestTime = TestTime;
      TestTime__is_set = true;
    }

    protected void setTestTime(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("TestTime", "urn:sobject.tooling.soap.sforce.com","TestTime","http://www.w3.org/2001/XMLSchema","int",0,1,true))) {
        setTestTime((java.lang.Integer)__typeMapper.readObject(__in, _lookupTypeInfo("TestTime", "urn:sobject.tooling.soap.sforce.com","TestTime","http://www.w3.org/2001/XMLSchema","int",0,1,true), java.lang.Integer.class));
      }
    }

    private void writeFieldTestTime(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("TestTime", "urn:sobject.tooling.soap.sforce.com","TestTime","http://www.w3.org/2001/XMLSchema","int",0,1,true), TestTime, TestTime__is_set);
    }

    /**
     * element : User of type {urn:sobject.tooling.soap.sforce.com}User
     * java type: com.sforce.soap.tooling.sobject.User
     */
    private boolean User__is_set = false;

    private com.sforce.soap.tooling.sobject.User User;

    public com.sforce.soap.tooling.sobject.User getUser() {
      return User;
    }

    public void setUser(com.sforce.soap.tooling.sobject.User User) {
      this.User = User;
      User__is_set = true;
    }

    protected void setUser(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("User", "urn:sobject.tooling.soap.sforce.com","User","urn:sobject.tooling.soap.sforce.com","User",0,1,true))) {
        setUser((com.sforce.soap.tooling.sobject.User)__typeMapper.readObject(__in, _lookupTypeInfo("User", "urn:sobject.tooling.soap.sforce.com","User","urn:sobject.tooling.soap.sforce.com","User",0,1,true), com.sforce.soap.tooling.sobject.User.class));
      }
    }

    private void writeFieldUser(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("User", "urn:sobject.tooling.soap.sforce.com","User","urn:sobject.tooling.soap.sforce.com","User",0,1,true), User, User__is_set);
    }

    /**
     * element : UserId of type {urn:tooling.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private boolean UserId__is_set = false;

    private java.lang.String UserId;

    public java.lang.String getUserId() {
      return UserId;
    }

    public void setUserId(java.lang.String UserId) {
      this.UserId = UserId;
      UserId__is_set = true;
    }

    protected void setUserId(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("UserId", "urn:sobject.tooling.soap.sforce.com","UserId","urn:tooling.soap.sforce.com","ID",0,1,true))) {
        setUserId(__typeMapper.readString(__in, _lookupTypeInfo("UserId", "urn:sobject.tooling.soap.sforce.com","UserId","urn:tooling.soap.sforce.com","ID",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldUserId(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("UserId", "urn:sobject.tooling.soap.sforce.com","UserId","urn:tooling.soap.sforce.com","ID",0,1,true), UserId, UserId__is_set);
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      __typeMapper.writeXsiType(__out, "urn:sobject.tooling.soap.sforce.com", "ApexTestRunResult");
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       super.writeFields(__out, __typeMapper);
       writeFields1(__out, __typeMapper);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        super.loadFields(__in, __typeMapper);
        loadFields1(__in, __typeMapper);
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[ApexTestRunResult ");
      sb.append(super.toString());
      toString1(sb);

      sb.append("]\n");
      return sb.toString();
    }

    private void toStringHelper(StringBuilder sb, String name, Object value) {
      sb.append(' ').append(name).append("='").append(com.sforce.ws.util.Verbose.toString(value)).append("'\n");
    }

    private void writeFields1(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      writeFieldAsyncApexJob(__out, __typeMapper);
      writeFieldAsyncApexJobId(__out, __typeMapper);
      writeFieldClassesCompleted(__out, __typeMapper);
      writeFieldClassesEnqueued(__out, __typeMapper);
      writeFieldCreatedBy(__out, __typeMapper);
      writeFieldCreatedById(__out, __typeMapper);
      writeFieldCreatedDate(__out, __typeMapper);
      writeFieldEndTime(__out, __typeMapper);
      writeFieldIsAllTests(__out, __typeMapper);
      writeFieldIsDeleted(__out, __typeMapper);
      writeFieldJobName(__out, __typeMapper);
      writeFieldLastModifiedBy(__out, __typeMapper);
      writeFieldLastModifiedById(__out, __typeMapper);
      writeFieldLastModifiedDate(__out, __typeMapper);
      writeFieldMethodsCompleted(__out, __typeMapper);
      writeFieldMethodsEnqueued(__out, __typeMapper);
      writeFieldMethodsFailed(__out, __typeMapper);
      writeFieldSource(__out, __typeMapper);
      writeFieldStartTime(__out, __typeMapper);
      writeFieldStatus(__out, __typeMapper);
      writeFieldSystemModstamp(__out, __typeMapper);
      writeFieldTestTime(__out, __typeMapper);
      writeFieldUser(__out, __typeMapper);
      writeFieldUserId(__out, __typeMapper);
    }

    private void loadFields1(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      setAsyncApexJob(__in, __typeMapper);
      setAsyncApexJobId(__in, __typeMapper);
      setClassesCompleted(__in, __typeMapper);
      setClassesEnqueued(__in, __typeMapper);
      setCreatedBy(__in, __typeMapper);
      setCreatedById(__in, __typeMapper);
      setCreatedDate(__in, __typeMapper);
      setEndTime(__in, __typeMapper);
      setIsAllTests(__in, __typeMapper);
      setIsDeleted(__in, __typeMapper);
      setJobName(__in, __typeMapper);
      setLastModifiedBy(__in, __typeMapper);
      setLastModifiedById(__in, __typeMapper);
      setLastModifiedDate(__in, __typeMapper);
      setMethodsCompleted(__in, __typeMapper);
      setMethodsEnqueued(__in, __typeMapper);
      setMethodsFailed(__in, __typeMapper);
      setSource(__in, __typeMapper);
      setStartTime(__in, __typeMapper);
      setStatus(__in, __typeMapper);
      setSystemModstamp(__in, __typeMapper);
      setTestTime(__in, __typeMapper);
      setUser(__in, __typeMapper);
      setUserId(__in, __typeMapper);
    }

    private void toString1(StringBuilder sb) {
      toStringHelper(sb, "AsyncApexJob", AsyncApexJob);
      toStringHelper(sb, "AsyncApexJobId", AsyncApexJobId);
      toStringHelper(sb, "ClassesCompleted", ClassesCompleted);
      toStringHelper(sb, "ClassesEnqueued", ClassesEnqueued);
      toStringHelper(sb, "CreatedBy", CreatedBy);
      toStringHelper(sb, "CreatedById", CreatedById);
      toStringHelper(sb, "CreatedDate", CreatedDate);
      toStringHelper(sb, "EndTime", EndTime);
      toStringHelper(sb, "IsAllTests", IsAllTests);
      toStringHelper(sb, "IsDeleted", IsDeleted);
      toStringHelper(sb, "JobName", JobName);
      toStringHelper(sb, "LastModifiedBy", LastModifiedBy);
      toStringHelper(sb, "LastModifiedById", LastModifiedById);
      toStringHelper(sb, "LastModifiedDate", LastModifiedDate);
      toStringHelper(sb, "MethodsCompleted", MethodsCompleted);
      toStringHelper(sb, "MethodsEnqueued", MethodsEnqueued);
      toStringHelper(sb, "MethodsFailed", MethodsFailed);
      toStringHelper(sb, "Source", Source);
      toStringHelper(sb, "StartTime", StartTime);
      toStringHelper(sb, "Status", Status);
      toStringHelper(sb, "SystemModstamp", SystemModstamp);
      toStringHelper(sb, "TestTime", TestTime);
      toStringHelper(sb, "User", User);
      toStringHelper(sb, "UserId", UserId);
    }


}
