/*
 [The "BSD licence"]
 Copyright (c) 2019 Kevin Jones
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions
 are met:
 1. Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.
 2. Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in the
    documentation and/or other materials provided with the distribution.
 3. The name of the author may not be used to endorse or promote products
    derived from this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
package com.nawforce.platform.ConnectApi;

import com.nawforce.platform.System.Boolean;
import com.nawforce.platform.System.Integer;
import com.nawforce.platform.System.List;
import com.nawforce.platform.System.String;

@SuppressWarnings("unused")
public class ChatterFeeds {



	public static ChatterStream createStream(String communityId, ChatterStreamInput streamInput) {throw new java.lang.UnsupportedOperationException();}
	public static void deleteComment(String communityId, String commentId) {throw new java.lang.UnsupportedOperationException();}
	public static void deleteFeedElement(String communityId, String feedElementId) {throw new java.lang.UnsupportedOperationException();}
	public static void deleteFeedItem(String communityId, String feedItemId) {throw new java.lang.UnsupportedOperationException();}
	public static void deleteLike(String communityId, String likeId) {throw new java.lang.UnsupportedOperationException();}
	public static void deleteStream(String communityId, String streamId) {throw new java.lang.UnsupportedOperationException();}
	public static Comment getComment(String communityId, String commentId) {throw new java.lang.UnsupportedOperationException();}
	public static List<BatchResult> getCommentBatch(String communityId, List<String> commentIds) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElement getCommentInContext(String communityId, String commentId, Integer pageSize) {throw new java.lang.UnsupportedOperationException();}
	public static CommentPage getCommentsForFeedElement(String communityId, String feedElementId) {throw new java.lang.UnsupportedOperationException();}
	public static CommentPage getCommentsForFeedElement(String communityId, String feedElementId, Boolean threadedCommentsCollapsed) {throw new java.lang.UnsupportedOperationException();}
	public static CommentPage getCommentsForFeedElement(String communityId, String feedElementId, Boolean threadedCommentsCollapsed, FeedCommentSortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static CommentsCapability getCommentsForFeedElement(String communityId, String feedElementId, FeedCommentSortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static CommentsCapability getCommentsForFeedElement(String communityId, String feedElementId, FeedCommentSortOrder sortParam, Boolean threadedCommentsCollapsed) {throw new java.lang.UnsupportedOperationException();}
	public static CommentPage getCommentsForFeedElement(String communityId, String feedElementId, String pageParam, Integer pageSize) {throw new java.lang.UnsupportedOperationException();}
	public static CommentPage getCommentsForFeedElement(String communityId, String feedElementId, String pageParam, Integer pageSize, Boolean threadedCommentsCollapsed) {throw new java.lang.UnsupportedOperationException();}
	public static CommentPage getCommentsForFeedElement(String communityId, String feedElementId, String pageParam, Integer pageSize, Boolean threadedCommentsCollapsed, FeedCommentSortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static CommentPage getCommentsForFeedItem(String communityId, String feedItemId) {throw new java.lang.UnsupportedOperationException();}
	public static CommentPage getCommentsForFeedItem(String communityId, String feedItemId, String pageParam, Integer pageSize) {throw new java.lang.UnsupportedOperationException();}
	public static ExtensionDefinitions getExtensions(String communityId, String pageParam, Integer pageSize) {throw new java.lang.UnsupportedOperationException();}
	public static Feed getFeed(String communityId, FeedType feedType) {throw new java.lang.UnsupportedOperationException();}
	public static Feed getFeed(String communityId, FeedType feedType, FeedSortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static Feed getFeed(String communityId, FeedType feedType, String subjectId) {throw new java.lang.UnsupportedOperationException();}
	public static Feed getFeed(String communityId, FeedType feedType, String subjectId, FeedSortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static FeedDirectory getFeedDirectory(String communityId) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElement getFeedElement(String communityId, String feedElementId) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElement getFeedElement(String communityId, String feedElementId, Boolean threadedCommentsCollapsed) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElement getFeedElement(String communityId, String feedElementId, Boolean threadedCommentsCollapsed, FeedCommentSortOrder commentSort) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElement getFeedElement(String communityId, String feedElementId, FeedCommentSortOrder commentSort) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElement getFeedElement(String communityId, String feedElementId, Integer recentCommentCount, Integer elementsPerBundle) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElement getFeedElement(String communityId, String feedElementId, Integer recentCommentCount, Integer elementsPerBundle, Boolean threadedCommentsCollapsed) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElement getFeedElement(String communityId, String feedElementId, Integer recentCommentCount, Integer elementsPerBundle, Boolean threadedCommentsCollapsed, FeedCommentSortOrder commentSort) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElement getFeedElement(String communityId, String feedElementId, Integer recentCommentCount, Integer elementsPerBundle, FeedCommentSortOrder commentSort) {throw new java.lang.UnsupportedOperationException();}
	public static List<BatchResult> getFeedElementBatch(String communityId, List<String> feedElementIds) {throw new java.lang.UnsupportedOperationException();}
	public static PollCapability getFeedElementPoll(String communityId, String feedElementId) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsFromBundle(String communityId, String feedElementId) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsFromBundle(String communityId, String feedElementId, String pageParam, Integer pageSize, Integer elementsPerBundle, Integer recentCommentCount) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsFromFeed(String communityId, FeedType feedType) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsFromFeed(String communityId, FeedType feedType, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsFromFeed(String communityId, FeedType feedType, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, FeedFilter filter) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsFromFeed(String communityId, FeedType feedType, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, FeedFilter filter, Boolean threadedCommentsCollapsed) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsFromFeed(String communityId, FeedType feedType, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String customFilter) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsFromFeed(String communityId, FeedType feedType, String pageParam, Integer pageSize, FeedSortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsFromFeed(String communityId, FeedType feedType, String subjectId) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsFromFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsFromFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, Boolean showInternalOnly) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsFromFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, FeedFilter filter) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsFromFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, FeedFilter filter, Boolean threadedCommentsCollapsed) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsFromFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String customFilter) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsFromFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, Integer elementsPerBundle, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, Boolean showInternalOnly) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsFromFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, Integer elementsPerBundle, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, Boolean showInternalOnly, FeedFilter filter) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsFromFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, Integer elementsPerBundle, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, Boolean showInternalOnly, FeedFilter filter, Boolean threadedCommentsCollapsed) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsFromFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, Integer elementsPerBundle, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, Boolean showInternalOnly, String customFilter) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsFromFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, Integer elementsPerBundle, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, Boolean showInternalOnly, String customFilter, Boolean threadedCommentsCollapsed) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsFromFeed(String communityId, FeedType feedType, String subjectId, String pageParam, Integer pageSize, FeedSortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsFromFilterFeed(String communityId, String subjectId, String keyPrefix) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsFromFilterFeed(String communityId, String subjectId, String keyPrefix, Integer recentCommentCount, Integer elementsPerBundle, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsFromFilterFeed(String communityId, String subjectId, String keyPrefix, String pageParam, Integer pageSize, FeedSortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsFromFilterFeedUpdatedSince(String communityId, String subjectId, String keyPrefix, Integer recentCommentCount, Integer elementsPerBundle, FeedDensity density, String pageParam, Integer pageSize, String updatedSince) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsUpdatedSince(String communityId, FeedType feedType, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, String updatedSince) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsUpdatedSince(String communityId, FeedType feedType, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, String updatedSince, FeedFilter filter) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsUpdatedSince(String communityId, FeedType feedType, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, String updatedSince, String customFilter) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsUpdatedSince(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, String updatedSince) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsUpdatedSince(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, String updatedSince, Boolean showInternalOnly) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsUpdatedSince(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, Integer elementsPerBundle, FeedDensity density, String pageParam, Integer pageSize, String updatedSince, Boolean showInternalOnly) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsUpdatedSince(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, Integer elementsPerBundle, FeedDensity density, String pageParam, Integer pageSize, String updatedSince, Boolean showInternalOnly, FeedFilter filter) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsUpdatedSince(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, Integer elementsPerBundle, FeedDensity density, String pageParam, Integer pageSize, String updatedSince, Boolean showInternalOnly, String customFilter) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsUpdatedSince(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, Integer elementsPerBundle, FeedDensity density, String pageParam, Integer pageSize, String updatedSince, FeedFilter filter) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getFeedElementsUpdatedSince(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, Integer elementsPerBundle, FeedDensity density, String pageParam, Integer pageSize, String updatedSince, String customFilter) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItem getFeedItem(String communityId, String feedItemId) {throw new java.lang.UnsupportedOperationException();}
	public static List<BatchResult> getFeedItemBatch(String communityId, List<String> feedItemIds) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage getFeedItemsFromFeed(String communityId, FeedType feedType) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage getFeedItemsFromFeed(String communityId, FeedType feedType, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage getFeedItemsFromFeed(String communityId, FeedType feedType, String pageParam, Integer pageSize, FeedSortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage getFeedItemsFromFeed(String communityId, FeedType feedType, String subjectId) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage getFeedItemsFromFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage getFeedItemsFromFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, Boolean showInternalOnly) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage getFeedItemsFromFeed(String communityId, FeedType feedType, String subjectId, String pageParam, Integer pageSize, FeedSortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage getFeedItemsFromFilterFeed(String communityId, String subjectId, String keyPrefix) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage getFeedItemsFromFilterFeed(String communityId, String subjectId, String keyPrefix, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage getFeedItemsFromFilterFeed(String communityId, String subjectId, String keyPrefix, String pageParam, Integer pageSize, FeedSortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage getFeedItemsFromFilterFeedUpdatedSince(String communityId, String subjectId, String keyPrefix, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, String updatedSince) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage getFeedItemsUpdatedSince(String communityId, FeedType feedType, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, String updatedSince) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage getFeedItemsUpdatedSince(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, String updatedSince) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage getFeedItemsUpdatedSince(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, String updatedSince, Boolean showInternalOnly) {throw new java.lang.UnsupportedOperationException();}
	public static FeedPoll getFeedPoll(String communityId, String feedItemId) {throw new java.lang.UnsupportedOperationException();}
	public static Feed getFeedWithFeedElements(String communityId, FeedType feedType, Integer pageSize) {throw new java.lang.UnsupportedOperationException();}
	public static Feed getFeedWithFeedElements(String communityId, FeedType feedType, Integer pageSize, Integer recentCommentCount) {throw new java.lang.UnsupportedOperationException();}
	public static Feed getFilterFeed(String communityId, String subjectId, String keyPrefix) {throw new java.lang.UnsupportedOperationException();}
	public static Feed getFilterFeed(String communityId, String subjectId, String keyPrefix, FeedSortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static FeedDirectory getFilterFeedDirectory(String communityId, String subjectId) {throw new java.lang.UnsupportedOperationException();}
	public static ChatterLike getLike(String communityId, String likeId) {throw new java.lang.UnsupportedOperationException();}
	public static ChatterLikePage getLikesForComment(String communityId, String commentId) {throw new java.lang.UnsupportedOperationException();}
	public static ChatterLikePage getLikesForComment(String communityId, String commentId, Integer pageParam, Integer pageSize) {throw new java.lang.UnsupportedOperationException();}
	public static ChatterLikePage getLikesForFeedElement(String communityId, String feedElementId) {throw new java.lang.UnsupportedOperationException();}
	public static ChatterLikePage getLikesForFeedElement(String communityId, String feedElementId, Integer pageParam, Integer pageSize) {throw new java.lang.UnsupportedOperationException();}
	public static ChatterLikePage getLikesForFeedItem(String communityId, String feedItemId) {throw new java.lang.UnsupportedOperationException();}
	public static ChatterLikePage getLikesForFeedItem(String communityId, String feedItemId, Integer pageParam, Integer pageSize) {throw new java.lang.UnsupportedOperationException();}
	public static LinkMetadataCollection getLinkMetadata(String communityId, String urls) {throw new java.lang.UnsupportedOperationException();}
	public static PinnedFeedElements getPinnedFeedElementsFromFeed(String communityId, FeedType feedType, String subjectId) {throw new java.lang.UnsupportedOperationException();}
	public static ReadByPage getReadByForFeedElement(String communityId, String feedElementId) {throw new java.lang.UnsupportedOperationException();}
	public static ReadByPage getReadByForFeedElement(String communityId, String feedElementId, String pageParam, Integer pageSize) {throw new java.lang.UnsupportedOperationException();}
	public static RelatedFeedPosts getRelatedPosts(String communityId, String feedElementId, RelatedFeedPostType filter, Integer maxResults) {throw new java.lang.UnsupportedOperationException();}
	public static ChatterStream getStream(String communityId, String streamId) {throw new java.lang.UnsupportedOperationException();}
	public static ChatterStream getStream(String communityId, String streamId, Boolean globalScope) {throw new java.lang.UnsupportedOperationException();}
	public static ChatterStreamPage getStreams(String communityId) {throw new java.lang.UnsupportedOperationException();}
	public static ChatterStreamPage getStreams(String communityId, SortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static ChatterStreamPage getStreams(String communityId, Integer pageParam, Integer pageSize) {throw new java.lang.UnsupportedOperationException();}
	public static ChatterStreamPage getStreams(String communityId, Integer pageParam, Integer pageSize, SortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static ChatterStreamPage getStreams(String communityId, Integer pageParam, Integer pageSize, SortOrder sortParam, Boolean globalScope) {throw new java.lang.UnsupportedOperationException();}
	public static SupportedEmojis getSupportedEmojis() {throw new java.lang.UnsupportedOperationException();}
	public static CommentPage getThreadsForFeedComment(String communityId, String commentId) {throw new java.lang.UnsupportedOperationException();}
	public static CommentsCapability getThreadsForFeedComment(String communityId, String commentId, Boolean threadedCommentsCollapsed) {throw new java.lang.UnsupportedOperationException();}
	public static CommentPage getThreadsForFeedComment(String communityId, String commentId, String pageParam, Integer pageSize) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getTopUnansweredQuestions(String communityId) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getTopUnansweredQuestions(String communityId, FeedFilter filter) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getTopUnansweredQuestions(String communityId, FeedFilter filter, Integer pageSize) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage getTopUnansweredQuestions(String communityId, Integer pageSize) {throw new java.lang.UnsupportedOperationException();}
	public static VotePage getVotesForComment(String communityId, String commentId, UpDownVoteValue vote) {throw new java.lang.UnsupportedOperationException();}
	public static VotePage getVotesForComment(String communityId, String commentId, UpDownVoteValue vote, Integer pageParam, Integer pageSize) {throw new java.lang.UnsupportedOperationException();}
	public static VotePage getVotesForFeedElement(String communityId, String feedElementId, UpDownVoteValue vote) {throw new java.lang.UnsupportedOperationException();}
	public static VotePage getVotesForFeedElement(String communityId, String feedElementId, UpDownVoteValue vote, Integer pageParam, Integer pageSize) {throw new java.lang.UnsupportedOperationException();}
	public static FeedEntityIsEditable isCommentEditableByMe(String communityId, String commentId) {throw new java.lang.UnsupportedOperationException();}
	public static FeedEntityIsEditable isFeedElementEditableByMe(String communityId, String feedElementId) {throw new java.lang.UnsupportedOperationException();}
	public static FeedModifiedInfo isModified(String communityId, FeedType feedType, String subjectId, String since) {throw new java.lang.UnsupportedOperationException();}
	public static ChatterLike likeComment(String communityId, String commentId) {throw new java.lang.UnsupportedOperationException();}
	public static ChatterLike likeFeedElement(String communityId, String feedElementId) {throw new java.lang.UnsupportedOperationException();}
	public static ChatterLike likeFeedItem(String communityId, String feedItemId) {throw new java.lang.UnsupportedOperationException();}
	public static Comment postComment(String communityId, String feedItemId, CommentInput comment, BinaryInput feedItemFileUpload) {throw new java.lang.UnsupportedOperationException();}
	public static Comment postComment(String communityId, String feedItemId, String text) {throw new java.lang.UnsupportedOperationException();}
	public static Comment postCommentToFeedElement(String communityId, String feedElementId, CommentInput comment, BinaryInput feedElementFileUpload) {throw new java.lang.UnsupportedOperationException();}
	public static Comment postCommentToFeedElement(String communityId, String feedElementId, String text) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElement postFeedElement(String communityId, FeedElementInput feedElement) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElement postFeedElement(String communityId, FeedElementInput feedElement, BinaryInput feedElementFileUpload) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElement postFeedElement(String communityId, String subjectId, FeedElementType feedElementType, String text) {throw new java.lang.UnsupportedOperationException();}
	public static List<BatchResult> postFeedElementBatch(String communityId, List<BatchInput> feedElements) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItem postFeedItem(String communityId, FeedType feedType, String subjectId, FeedItemInput feedItem, BinaryInput feedItemFileUpload) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItem postFeedItem(String communityId, FeedType feedType, String subjectId, String text) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElement publishDraftFeedElement(String communityId, String feedElementId, FeedElementInput feedElement) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage searchFeedElements(String communityId, String q) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage searchFeedElements(String communityId, String q, Boolean threadedCommentsCollapsed) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage searchFeedElements(String communityId, String q, FeedSortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage searchFeedElements(String communityId, String q, Integer recentCommentCount, String pageParam, Integer pageSize, FeedSortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage searchFeedElements(String communityId, String q, String pageParam, Integer pageSize) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage searchFeedElements(String communityId, String q, String pageParam, Integer pageSize, Boolean threadedCommentsCollapsed) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage searchFeedElements(String communityId, String q, String pageParam, Integer pageSize, FeedSortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage searchFeedElementsInFeed(String communityId, FeedType feedType, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage searchFeedElementsInFeed(String communityId, FeedType feedType, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, FeedFilter filter) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage searchFeedElementsInFeed(String communityId, FeedType feedType, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, String customFilter) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage searchFeedElementsInFeed(String communityId, FeedType feedType, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage searchFeedElementsInFeed(String communityId, FeedType feedType, String q) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage searchFeedElementsInFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage searchFeedElementsInFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, Boolean showInternalOnly) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage searchFeedElementsInFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, Boolean showInternalOnly, FeedFilter filter) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage searchFeedElementsInFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, Boolean showInternalOnly, String customFilter) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage searchFeedElementsInFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, FeedFilter filter) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage searchFeedElementsInFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, String customFilter) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage searchFeedElementsInFeed(String communityId, FeedType feedType, String subjectId, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage searchFeedElementsInFeed(String communityId, FeedType feedType, String subjectId, String q) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage searchFeedElementsInFilterFeed(String communityId, String subjectId, String keyPrefix, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage searchFeedElementsInFilterFeed(String communityId, String subjectId, String keyPrefix, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElementPage searchFeedElementsInFilterFeed(String communityId, String subjectId, String keyPrefix, String q) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage searchFeedItems(String communityId, String q) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage searchFeedItems(String communityId, String q, FeedSortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage searchFeedItems(String communityId, String q, Integer recentCommentCount, String pageParam, Integer pageSize, FeedSortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage searchFeedItems(String communityId, String q, String pageParam, Integer pageSize) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage searchFeedItems(String communityId, String q, String pageParam, Integer pageSize, FeedSortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage searchFeedItemsInFeed(String communityId, FeedType feedType, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage searchFeedItemsInFeed(String communityId, FeedType feedType, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage searchFeedItemsInFeed(String communityId, FeedType feedType, String q) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage searchFeedItemsInFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage searchFeedItemsInFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, Boolean showInternalOnly) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage searchFeedItemsInFeed(String communityId, FeedType feedType, String subjectId, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage searchFeedItemsInFeed(String communityId, FeedType feedType, String subjectId, String q) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage searchFeedItemsInFilterFeed(String communityId, String subjectId, String keyPrefix, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage searchFeedItemsInFilterFeed(String communityId, String subjectId, String keyPrefix, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItemPage searchFeedItemsInFilterFeed(String communityId, String subjectId, String keyPrefix, String q) {throw new java.lang.UnsupportedOperationException();}
	public static ChatterStreamPage searchStreams(String communityId, String q) {throw new java.lang.UnsupportedOperationException();}
	public static ChatterStreamPage searchStreams(String communityId, String q, SortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static ChatterStreamPage searchStreams(String communityId, String q, Integer pageParam, Integer pageSize) {throw new java.lang.UnsupportedOperationException();}
	public static ChatterStreamPage searchStreams(String communityId, String q, Integer pageParam, Integer pageSize, SortOrder sortParam) {throw new java.lang.UnsupportedOperationException();}
	public static ChatterStreamPage searchStreams(String communityId, String q, Integer pageParam, Integer pageSize, SortOrder sortParam, Boolean globalScope) {throw new java.lang.UnsupportedOperationException();}
	public static VerifiedCapability setCommentIsVerified(String communityId, String commentId, Boolean isVerified) {throw new java.lang.UnsupportedOperationException();}
	public static VerifiedCapability setCommentIsVerifiedByAnonymized(String communityId, String commentId, Boolean isVerified, Boolean isVerifiedByAnonymized) {throw new java.lang.UnsupportedOperationException();}
	public static UpDownVoteCapability setCommentVote(String communityId, String commentId, UpDownVoteCapabilityInput upDownVote) {throw new java.lang.UnsupportedOperationException();}
	public static StatusCapability setFeedCommentStatus(String communityId, String commentId, StatusCapabilityInput status) {throw new java.lang.UnsupportedOperationException();}
	public static CloseCapability setFeedElementIsClosed(String communityId, String feedElementId, Boolean isClosed) {throw new java.lang.UnsupportedOperationException();}
	public static UpDownVoteCapability setFeedElementVote(String communityId, String feedElementId, UpDownVoteCapabilityInput upDownVote) {throw new java.lang.UnsupportedOperationException();}
	public static StatusCapability setFeedEntityStatus(String communityId, String feedElementId, StatusCapabilityInput status) {throw new java.lang.UnsupportedOperationException();}
	public static MuteCapability setIsMutedByMe(String communityId, String feedElementId, Boolean isMutedByMe) {throw new java.lang.UnsupportedOperationException();}
	public static ReadByCapability setIsReadByMe(String communityId, String feedElementId, Boolean isReadByMe) {throw new java.lang.UnsupportedOperationException();}
	public static ReadByCapability setIsReadByMe(String communityId, String feedElementId, ReadByCapabilityInput readBy) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsFromFeed(String communityId, FeedType feedType, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsFromFeed(String communityId, FeedType feedType, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsFromFeed(String communityId, FeedType feedType, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, FeedFilter filter, Boolean threadedCommentsCollapsed, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsFromFeed(String communityId, FeedType feedType, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, FeedFilter filter, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsFromFeed(String communityId, FeedType feedType, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String customFilter, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsFromFeed(String communityId, FeedType feedType, String pageParam, Integer pageSize, FeedSortOrder sortParam, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsFromFeed(String communityId, FeedType feedType, String subjectId, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsFromFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, Boolean showInternalOnly, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsFromFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsFromFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, FeedFilter filter, Boolean threadedCommentsCollapsed, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsFromFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, FeedFilter filter, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsFromFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String customFilter, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsFromFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, Integer elementsPerBundle, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, Boolean showInternalOnly, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsFromFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, Integer elementsPerBundle, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, Boolean showInternalOnly, FeedFilter filter, Boolean threadedCommentsCollapsed, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsFromFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, Integer elementsPerBundle, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, Boolean showInternalOnly, FeedFilter filter, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsFromFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, Integer elementsPerBundle, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, Boolean showInternalOnly, String customFilter, Boolean threadedCommentsCollapsed, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsFromFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, Integer elementsPerBundle, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, Boolean showInternalOnly, String customFilter, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsFromFeed(String communityId, FeedType feedType, String subjectId, String pageParam, Integer pageSize, FeedSortOrder sortParam, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsFromFilterFeed(String communityId, String subjectId, String keyPrefix, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsFromFilterFeed(String communityId, String subjectId, String keyPrefix, Integer recentCommentCount, Integer elementsPerBundle, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsFromFilterFeed(String communityId, String subjectId, String keyPrefix, String pageParam, Integer pageSize, FeedSortOrder sortParam, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsFromFilterFeedUpdatedSince(String communityId, String subjectId, String keyPrefix, Integer recentCommentCount, Integer elementsPerBundle, FeedDensity density, String pageParam, Integer pageSize, String updatedSince, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsUpdatedSince(String communityId, FeedType feedType, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, String updatedSince, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsUpdatedSince(String communityId, FeedType feedType, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, String updatedSince, FeedFilter filter, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsUpdatedSince(String communityId, FeedType feedType, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, String updatedSince, String customFilter, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsUpdatedSince(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, String updatedSince, Boolean showInternalOnly, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsUpdatedSince(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, String updatedSince, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsUpdatedSince(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, Integer elementsPerBundle, FeedDensity density, String pageParam, Integer pageSize, String updatedSince, Boolean showInternalOnly, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsUpdatedSince(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, Integer elementsPerBundle, FeedDensity density, String pageParam, Integer pageSize, String updatedSince, Boolean showInternalOnly, FeedFilter filter, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsUpdatedSince(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, Integer elementsPerBundle, FeedDensity density, String pageParam, Integer pageSize, String updatedSince, Boolean showInternalOnly, String customFilter, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsUpdatedSince(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, Integer elementsPerBundle, FeedDensity density, String pageParam, Integer pageSize, String updatedSince, FeedFilter filter, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedElementsUpdatedSince(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, Integer elementsPerBundle, FeedDensity density, String pageParam, Integer pageSize, String updatedSince, String customFilter, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedItemsFromFeed(String communityId, FeedType feedType, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedItemsFromFeed(String communityId, FeedType feedType, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedItemsFromFeed(String communityId, FeedType feedType, String pageParam, Integer pageSize, FeedSortOrder sortParam, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedItemsFromFeed(String communityId, FeedType feedType, String subjectId, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedItemsFromFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, Boolean showInternalOnly, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedItemsFromFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedItemsFromFeed(String communityId, FeedType feedType, String subjectId, String pageParam, Integer pageSize, FeedSortOrder sortParam, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedItemsFromFilterFeed(String communityId, String subjectId, String keyPrefix, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedItemsFromFilterFeed(String communityId, String subjectId, String keyPrefix, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedItemsFromFilterFeed(String communityId, String subjectId, String keyPrefix, String pageParam, Integer pageSize, FeedSortOrder sortParam, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedItemsFromFilterFeedUpdatedSince(String communityId, String subjectId, String keyPrefix, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, String updatedSince, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedItemsUpdatedSince(String communityId, FeedType feedType, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, String updatedSince, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedItemsUpdatedSince(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, String updatedSince, Boolean showInternalOnly, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetFeedItemsUpdatedSince(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, String updatedSince, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetRelatedPosts(String communityId, String feedElementId, RelatedFeedPostType filter, Integer maxResults, RelatedFeedPosts result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetTopUnansweredQuestions(String communityId, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetTopUnansweredQuestions(String communityId, FeedFilter filter, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetTopUnansweredQuestions(String communityId, FeedFilter filter, Integer pageSize, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestGetTopUnansweredQuestions(String communityId, Integer pageSize, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedElements(String communityId, String q, Boolean threadedCommentsCollapsed, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedElements(String communityId, String q, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedElements(String communityId, String q, FeedSortOrder sortParam, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedElements(String communityId, String q, Integer recentCommentCount, String pageParam, Integer pageSize, FeedSortOrder sortParam, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedElements(String communityId, String q, String pageParam, Integer pageSize, Boolean threadedCommentsCollapsed, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedElements(String communityId, String q, String pageParam, Integer pageSize, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedElements(String communityId, String q, String pageParam, Integer pageSize, FeedSortOrder sortParam, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedElementsInFeed(String communityId, FeedType feedType, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedElementsInFeed(String communityId, FeedType feedType, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, FeedFilter filter, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedElementsInFeed(String communityId, FeedType feedType, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, String customFilter, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedElementsInFeed(String communityId, FeedType feedType, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedElementsInFeed(String communityId, FeedType feedType, String q, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedElementsInFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, Boolean showInternalOnly, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedElementsInFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, Boolean showInternalOnly, FeedFilter filter, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedElementsInFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, Boolean showInternalOnly, String customFilter, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedElementsInFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedElementsInFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, FeedFilter filter, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedElementsInFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, String customFilter, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedElementsInFeed(String communityId, FeedType feedType, String subjectId, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedElementsInFeed(String communityId, FeedType feedType, String subjectId, String q, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedElementsInFilterFeed(String communityId, String subjectId, String keyPrefix, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedElementsInFilterFeed(String communityId, String subjectId, String keyPrefix, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedElementsInFilterFeed(String communityId, String subjectId, String keyPrefix, String q, FeedElementPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedItems(String communityId, String q, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedItems(String communityId, String q, FeedSortOrder sortParam, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedItems(String communityId, String q, Integer recentCommentCount, String pageParam, Integer pageSize, FeedSortOrder sortParam, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedItems(String communityId, String q, String pageParam, Integer pageSize, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedItems(String communityId, String q, String pageParam, Integer pageSize, FeedSortOrder sortParam, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedItemsInFeed(String communityId, FeedType feedType, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedItemsInFeed(String communityId, FeedType feedType, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedItemsInFeed(String communityId, FeedType feedType, String q, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedItemsInFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, Boolean showInternalOnly, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedItemsInFeed(String communityId, FeedType feedType, String subjectId, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedItemsInFeed(String communityId, FeedType feedType, String subjectId, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedItemsInFeed(String communityId, FeedType feedType, String subjectId, String q, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedItemsInFilterFeed(String communityId, String subjectId, String keyPrefix, Integer recentCommentCount, FeedDensity density, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedItemsInFilterFeed(String communityId, String subjectId, String keyPrefix, String pageParam, Integer pageSize, FeedSortOrder sortParam, String q, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchFeedItemsInFilterFeed(String communityId, String subjectId, String keyPrefix, String q, FeedItemPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchStreams(String communityId, String q, ChatterStreamPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchStreams(String communityId, String q, SortOrder sortParam, ChatterStreamPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchStreams(String communityId, String q, Integer pageParam, Integer pageSize, ChatterStreamPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchStreams(String communityId, String q, Integer pageParam, Integer pageSize, SortOrder sortParam, Boolean globalScope, ChatterStreamPage result) {throw new java.lang.UnsupportedOperationException();}
	public static void setTestSearchStreams(String communityId, String q, Integer pageParam, Integer pageSize, SortOrder sortParam, ChatterStreamPage result) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElement shareFeedElement(String communityId, String subjectId, FeedElementType feedElementType, String originalFeedElementId) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItem shareFeedItem(String communityId, FeedType feedType, String subjectId, String originalFeedItemId) {throw new java.lang.UnsupportedOperationException();}
	public static FeedItem updateBookmark(String communityId, String feedItemId, Boolean isBookmarkedByCurrentUser) {throw new java.lang.UnsupportedOperationException();}
	public static Comment updateComment(String communityId, String commentId, CommentInput comment) {throw new java.lang.UnsupportedOperationException();}
	public static DirectMessageCapability updateDirectMessage(String communityId, String feedElementId, DirectMessageCapabilityInput directMessage) {throw new java.lang.UnsupportedOperationException();}
	public static FeedElement updateFeedElement(String communityId, String feedElementId, FeedElementInput feedElement) {throw new java.lang.UnsupportedOperationException();}
	public static BookmarksCapability updateFeedElementBookmarks(String communityId, String feedElementId, Boolean isBookmarkedByCurrentUser) {throw new java.lang.UnsupportedOperationException();}
	public static BookmarksCapability updateFeedElementBookmarks(String communityId, String feedElementId, BookmarksCapabilityInput bookmarks) {throw new java.lang.UnsupportedOperationException();}
	public static List<BatchResult> updateFeedElementReadByCapabilityBatch(String communityId, List<String> feedElementIds, Boolean isReadByMe) {throw new java.lang.UnsupportedOperationException();}
	public static List<BatchResult> updateFeedElementReadByCapabilityBatch(String communityId, List<String> feedElementIds, ReadByCapabilityInput readBy) {throw new java.lang.UnsupportedOperationException();}
	public static ChatterLikePage updateLikeForComment(String communityId, String commentId, Boolean isLikedByCurrentUser) {throw new java.lang.UnsupportedOperationException();}
	public static ChatterLikePage updateLikeForFeedElement(String communityId, String feedElementId, Boolean isLikedByCurrentUser) {throw new java.lang.UnsupportedOperationException();}
	public static PinCapability updatePinnedFeedElements(String communityId, FeedType feedType, String subjectId, PinCapabilityInput pin) {throw new java.lang.UnsupportedOperationException();}
	public static ChatterStream updateStream(String communityId, String streamId, ChatterStreamInput streamInput) {throw new java.lang.UnsupportedOperationException();}
	public static PollCapability voteOnFeedElementPoll(String communityId, String feedElementId, String myChoiceId) {throw new java.lang.UnsupportedOperationException();}
	public static FeedPoll voteOnFeedPoll(String communityId, String feedItemId, String myChoiceId) {throw new java.lang.UnsupportedOperationException();}

}
