package com.sforce.soap.tooling;

/**
 * This is a generated class for the SObject Enterprise API.
 * Do not edit this file, as your changes will be lost.
 */
public class DescribeSoqlListView implements com.sforce.ws.bind.XMLizable {

    /**
     * Constructor
     */
    public DescribeSoqlListView() {}

    /* Cache the typeInfo instead of declaring static fields throughout*/
    private transient java.util.Map<String, com.sforce.ws.bind.TypeInfo> typeInfoCache = new java.util.HashMap<String, com.sforce.ws.bind.TypeInfo>();
    private com.sforce.ws.bind.TypeInfo _lookupTypeInfo(String fieldName, String namespace, String name, String typeNS, String type, int minOcc, int maxOcc, boolean elementForm) {
      com.sforce.ws.bind.TypeInfo typeInfo = typeInfoCache.get(fieldName);
      if (typeInfo == null) {
        typeInfo = new com.sforce.ws.bind.TypeInfo(namespace, name, typeNS, type, minOcc, maxOcc, elementForm);
        typeInfoCache.put(fieldName, typeInfo);
      }
      return typeInfo;
    }

    /**
     * element : columns of type {urn:tooling.soap.sforce.com}ListViewColumn
     * java type: com.sforce.soap.tooling.ListViewColumn[]
     */
    private boolean columns__is_set = false;

    private com.sforce.soap.tooling.ListViewColumn[] columns = new com.sforce.soap.tooling.ListViewColumn[0];

    public com.sforce.soap.tooling.ListViewColumn[] getColumns() {
      return columns;
    }

    public void setColumns(com.sforce.soap.tooling.ListViewColumn[] columns) {
      this.columns = columns;
      columns__is_set = true;
    }

    protected void setColumns(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("columns", "urn:tooling.soap.sforce.com","columns","urn:tooling.soap.sforce.com","ListViewColumn",0,-1,true))) {
        setColumns((com.sforce.soap.tooling.ListViewColumn[])__typeMapper.readObject(__in, _lookupTypeInfo("columns", "urn:tooling.soap.sforce.com","columns","urn:tooling.soap.sforce.com","ListViewColumn",0,-1,true), com.sforce.soap.tooling.ListViewColumn[].class));
      }
    }

    private void writeFieldColumns(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("columns", "urn:tooling.soap.sforce.com","columns","urn:tooling.soap.sforce.com","ListViewColumn",0,-1,true), columns, columns__is_set);
    }

    /**
     * element : id of type {urn:tooling.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private boolean id__is_set = false;

    private java.lang.String id;

    public java.lang.String getId() {
      return id;
    }

    public void setId(java.lang.String id) {
      this.id = id;
      id__is_set = true;
    }

    protected void setId(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("id", "urn:tooling.soap.sforce.com","id","urn:tooling.soap.sforce.com","ID",1,1,true))) {
        setId(__typeMapper.readString(__in, _lookupTypeInfo("id", "urn:tooling.soap.sforce.com","id","urn:tooling.soap.sforce.com","ID",1,1,true), java.lang.String.class));
      }
    }

    private void writeFieldId(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("id", "urn:tooling.soap.sforce.com","id","urn:tooling.soap.sforce.com","ID",1,1,true), id, id__is_set);
    }

    /**
     * element : orderBy of type {urn:tooling.soap.sforce.com}ListViewOrderBy
     * java type: com.sforce.soap.tooling.ListViewOrderBy[]
     */
    private boolean orderBy__is_set = false;

    private com.sforce.soap.tooling.ListViewOrderBy[] orderBy = new com.sforce.soap.tooling.ListViewOrderBy[0];

    public com.sforce.soap.tooling.ListViewOrderBy[] getOrderBy() {
      return orderBy;
    }

    public void setOrderBy(com.sforce.soap.tooling.ListViewOrderBy[] orderBy) {
      this.orderBy = orderBy;
      orderBy__is_set = true;
    }

    protected void setOrderBy(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("orderBy", "urn:tooling.soap.sforce.com","orderBy","urn:tooling.soap.sforce.com","ListViewOrderBy",0,-1,true))) {
        setOrderBy((com.sforce.soap.tooling.ListViewOrderBy[])__typeMapper.readObject(__in, _lookupTypeInfo("orderBy", "urn:tooling.soap.sforce.com","orderBy","urn:tooling.soap.sforce.com","ListViewOrderBy",0,-1,true), com.sforce.soap.tooling.ListViewOrderBy[].class));
      }
    }

    private void writeFieldOrderBy(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("orderBy", "urn:tooling.soap.sforce.com","orderBy","urn:tooling.soap.sforce.com","ListViewOrderBy",0,-1,true), orderBy, orderBy__is_set);
    }

    /**
     * element : query of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean query__is_set = false;

    private java.lang.String query;

    public java.lang.String getQuery() {
      return query;
    }

    public void setQuery(java.lang.String query) {
      this.query = query;
      query__is_set = true;
    }

    protected void setQuery(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("query", "urn:tooling.soap.sforce.com","query","http://www.w3.org/2001/XMLSchema","string",1,1,true))) {
        setQuery(__typeMapper.readString(__in, _lookupTypeInfo("query", "urn:tooling.soap.sforce.com","query","http://www.w3.org/2001/XMLSchema","string",1,1,true), java.lang.String.class));
      }
    }

    private void writeFieldQuery(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("query", "urn:tooling.soap.sforce.com","query","http://www.w3.org/2001/XMLSchema","string",1,1,true), query, query__is_set);
    }

    /**
     * element : relatedEntityId of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean relatedEntityId__is_set = false;

    private java.lang.String relatedEntityId;

    public java.lang.String getRelatedEntityId() {
      return relatedEntityId;
    }

    public void setRelatedEntityId(java.lang.String relatedEntityId) {
      this.relatedEntityId = relatedEntityId;
      relatedEntityId__is_set = true;
    }

    protected void setRelatedEntityId(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("relatedEntityId", "urn:tooling.soap.sforce.com","relatedEntityId","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setRelatedEntityId(__typeMapper.readString(__in, _lookupTypeInfo("relatedEntityId", "urn:tooling.soap.sforce.com","relatedEntityId","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldRelatedEntityId(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("relatedEntityId", "urn:tooling.soap.sforce.com","relatedEntityId","http://www.w3.org/2001/XMLSchema","string",0,1,true), relatedEntityId, relatedEntityId__is_set);
    }

    /**
     * element : scope of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean scope__is_set = false;

    private java.lang.String scope;

    public java.lang.String getScope() {
      return scope;
    }

    public void setScope(java.lang.String scope) {
      this.scope = scope;
      scope__is_set = true;
    }

    protected void setScope(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("scope", "urn:tooling.soap.sforce.com","scope","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setScope(__typeMapper.readString(__in, _lookupTypeInfo("scope", "urn:tooling.soap.sforce.com","scope","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldScope(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("scope", "urn:tooling.soap.sforce.com","scope","http://www.w3.org/2001/XMLSchema","string",0,1,true), scope, scope__is_set);
    }

    /**
     * element : scopeEntityId of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean scopeEntityId__is_set = false;

    private java.lang.String scopeEntityId;

    public java.lang.String getScopeEntityId() {
      return scopeEntityId;
    }

    public void setScopeEntityId(java.lang.String scopeEntityId) {
      this.scopeEntityId = scopeEntityId;
      scopeEntityId__is_set = true;
    }

    protected void setScopeEntityId(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("scopeEntityId", "urn:tooling.soap.sforce.com","scopeEntityId","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setScopeEntityId(__typeMapper.readString(__in, _lookupTypeInfo("scopeEntityId", "urn:tooling.soap.sforce.com","scopeEntityId","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldScopeEntityId(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("scopeEntityId", "urn:tooling.soap.sforce.com","scopeEntityId","http://www.w3.org/2001/XMLSchema","string",0,1,true), scopeEntityId, scopeEntityId__is_set);
    }

    /**
     * element : sobjectType of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean sobjectType__is_set = false;

    private java.lang.String sobjectType;

    public java.lang.String getSobjectType() {
      return sobjectType;
    }

    public void setSobjectType(java.lang.String sobjectType) {
      this.sobjectType = sobjectType;
      sobjectType__is_set = true;
    }

    protected void setSobjectType(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("sobjectType", "urn:tooling.soap.sforce.com","sobjectType","http://www.w3.org/2001/XMLSchema","string",1,1,true))) {
        setSobjectType(__typeMapper.readString(__in, _lookupTypeInfo("sobjectType", "urn:tooling.soap.sforce.com","sobjectType","http://www.w3.org/2001/XMLSchema","string",1,1,true), java.lang.String.class));
      }
    }

    private void writeFieldSobjectType(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("sobjectType", "urn:tooling.soap.sforce.com","sobjectType","http://www.w3.org/2001/XMLSchema","string",1,1,true), sobjectType, sobjectType__is_set);
    }

    /**
     * element : whereCondition of type {urn:tooling.soap.sforce.com}SoqlWhereCondition
     * java type: com.sforce.soap.tooling.SoqlWhereCondition
     */
    private boolean whereCondition__is_set = false;

    private com.sforce.soap.tooling.SoqlWhereCondition whereCondition;

    public com.sforce.soap.tooling.SoqlWhereCondition getWhereCondition() {
      return whereCondition;
    }

    public void setWhereCondition(com.sforce.soap.tooling.SoqlWhereCondition whereCondition) {
      this.whereCondition = whereCondition;
      whereCondition__is_set = true;
    }

    protected void setWhereCondition(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("whereCondition", "urn:tooling.soap.sforce.com","whereCondition","urn:tooling.soap.sforce.com","SoqlWhereCondition",0,1,true))) {
        setWhereCondition((com.sforce.soap.tooling.SoqlWhereCondition)__typeMapper.readObject(__in, _lookupTypeInfo("whereCondition", "urn:tooling.soap.sforce.com","whereCondition","urn:tooling.soap.sforce.com","SoqlWhereCondition",0,1,true), com.sforce.soap.tooling.SoqlWhereCondition.class));
      }
    }

    private void writeFieldWhereCondition(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("whereCondition", "urn:tooling.soap.sforce.com","whereCondition","urn:tooling.soap.sforce.com","SoqlWhereCondition",0,1,true), whereCondition, whereCondition__is_set);
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       writeFields1(__out, __typeMapper);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        loadFields1(__in, __typeMapper);
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[DescribeSoqlListView ");
      toString1(sb);

      sb.append("]\n");
      return sb.toString();
    }

    private void toStringHelper(StringBuilder sb, String name, Object value) {
      sb.append(' ').append(name).append("='").append(com.sforce.ws.util.Verbose.toString(value)).append("'\n");
    }

    private void writeFields1(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      writeFieldColumns(__out, __typeMapper);
      writeFieldId(__out, __typeMapper);
      writeFieldOrderBy(__out, __typeMapper);
      writeFieldQuery(__out, __typeMapper);
      writeFieldRelatedEntityId(__out, __typeMapper);
      writeFieldScope(__out, __typeMapper);
      writeFieldScopeEntityId(__out, __typeMapper);
      writeFieldSobjectType(__out, __typeMapper);
      writeFieldWhereCondition(__out, __typeMapper);
    }

    private void loadFields1(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      setColumns(__in, __typeMapper);
      setId(__in, __typeMapper);
      setOrderBy(__in, __typeMapper);
      setQuery(__in, __typeMapper);
      setRelatedEntityId(__in, __typeMapper);
      setScope(__in, __typeMapper);
      setScopeEntityId(__in, __typeMapper);
      setSobjectType(__in, __typeMapper);
      setWhereCondition(__in, __typeMapper);
    }

    private void toString1(StringBuilder sb) {
      toStringHelper(sb, "columns", columns);
      toStringHelper(sb, "id", id);
      toStringHelper(sb, "orderBy", orderBy);
      toStringHelper(sb, "query", query);
      toStringHelper(sb, "relatedEntityId", relatedEntityId);
      toStringHelper(sb, "scope", scope);
      toStringHelper(sb, "scopeEntityId", scopeEntityId);
      toStringHelper(sb, "sobjectType", sobjectType);
      toStringHelper(sb, "whereCondition", whereCondition);
    }


}
