package com.sforce.soap.tooling;

/**
 * This is a generated class for the SObject Enterprise API.
 * Do not edit this file, as your changes will be lost.
 */
public class Field implements com.sforce.ws.bind.XMLizable {

    /**
     * Constructor
     */
    public Field() {}

    /* Cache the typeInfo instead of declaring static fields throughout*/
    private transient java.util.Map<String, com.sforce.ws.bind.TypeInfo> typeInfoCache = new java.util.HashMap<String, com.sforce.ws.bind.TypeInfo>();
    private com.sforce.ws.bind.TypeInfo _lookupTypeInfo(String fieldName, String namespace, String name, String typeNS, String type, int minOcc, int maxOcc, boolean elementForm) {
      com.sforce.ws.bind.TypeInfo typeInfo = typeInfoCache.get(fieldName);
      if (typeInfo == null) {
        typeInfo = new com.sforce.ws.bind.TypeInfo(namespace, name, typeNS, type, minOcc, maxOcc, elementForm);
        typeInfoCache.put(fieldName, typeInfo);
      }
      return typeInfo;
    }

    /**
     * element : aggregatable of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean aggregatable__is_set = false;

    private boolean aggregatable;

    public boolean getAggregatable() {
      return aggregatable;
    }

    public boolean isAggregatable() {
      return aggregatable;
    }

    public void setAggregatable(boolean aggregatable) {
      this.aggregatable = aggregatable;
      aggregatable__is_set = true;
    }

    protected void setAggregatable(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("aggregatable", "urn:tooling.soap.sforce.com","aggregatable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setAggregatable(__typeMapper.readBoolean(__in, _lookupTypeInfo("aggregatable", "urn:tooling.soap.sforce.com","aggregatable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldAggregatable(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("aggregatable", "urn:tooling.soap.sforce.com","aggregatable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), aggregatable, aggregatable__is_set);
    }

    /**
     * element : aiPredictionField of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean aiPredictionField__is_set = false;

    private boolean aiPredictionField;

    public boolean getAiPredictionField() {
      return aiPredictionField;
    }

    public boolean isAiPredictionField() {
      return aiPredictionField;
    }

    public void setAiPredictionField(boolean aiPredictionField) {
      this.aiPredictionField = aiPredictionField;
      aiPredictionField__is_set = true;
    }

    protected void setAiPredictionField(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("aiPredictionField", "urn:tooling.soap.sforce.com","aiPredictionField","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setAiPredictionField(__typeMapper.readBoolean(__in, _lookupTypeInfo("aiPredictionField", "urn:tooling.soap.sforce.com","aiPredictionField","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldAiPredictionField(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("aiPredictionField", "urn:tooling.soap.sforce.com","aiPredictionField","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), aiPredictionField, aiPredictionField__is_set);
    }

    /**
     * element : autoNumber of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean autoNumber__is_set = false;

    private boolean autoNumber;

    public boolean getAutoNumber() {
      return autoNumber;
    }

    public boolean isAutoNumber() {
      return autoNumber;
    }

    public void setAutoNumber(boolean autoNumber) {
      this.autoNumber = autoNumber;
      autoNumber__is_set = true;
    }

    protected void setAutoNumber(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("autoNumber", "urn:tooling.soap.sforce.com","autoNumber","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setAutoNumber(__typeMapper.readBoolean(__in, _lookupTypeInfo("autoNumber", "urn:tooling.soap.sforce.com","autoNumber","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldAutoNumber(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("autoNumber", "urn:tooling.soap.sforce.com","autoNumber","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), autoNumber, autoNumber__is_set);
    }

    /**
     * element : byteLength of type {http://www.w3.org/2001/XMLSchema}int
     * java type: int
     */
    private boolean byteLength__is_set = false;

    private int byteLength;

    public int getByteLength() {
      return byteLength;
    }

    public void setByteLength(int byteLength) {
      this.byteLength = byteLength;
      byteLength__is_set = true;
    }

    protected void setByteLength(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("byteLength", "urn:tooling.soap.sforce.com","byteLength","http://www.w3.org/2001/XMLSchema","int",1,1,true))) {
        setByteLength((int)__typeMapper.readInt(__in, _lookupTypeInfo("byteLength", "urn:tooling.soap.sforce.com","byteLength","http://www.w3.org/2001/XMLSchema","int",1,1,true), int.class));
      }
    }

    private void writeFieldByteLength(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("byteLength", "urn:tooling.soap.sforce.com","byteLength","http://www.w3.org/2001/XMLSchema","int",1,1,true), byteLength, byteLength__is_set);
    }

    /**
     * element : calculated of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean calculated__is_set = false;

    private boolean calculated;

    public boolean getCalculated() {
      return calculated;
    }

    public boolean isCalculated() {
      return calculated;
    }

    public void setCalculated(boolean calculated) {
      this.calculated = calculated;
      calculated__is_set = true;
    }

    protected void setCalculated(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("calculated", "urn:tooling.soap.sforce.com","calculated","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setCalculated(__typeMapper.readBoolean(__in, _lookupTypeInfo("calculated", "urn:tooling.soap.sforce.com","calculated","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldCalculated(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("calculated", "urn:tooling.soap.sforce.com","calculated","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), calculated, calculated__is_set);
    }

    /**
     * element : calculatedFormula of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean calculatedFormula__is_set = false;

    private java.lang.String calculatedFormula;

    public java.lang.String getCalculatedFormula() {
      return calculatedFormula;
    }

    public void setCalculatedFormula(java.lang.String calculatedFormula) {
      this.calculatedFormula = calculatedFormula;
      calculatedFormula__is_set = true;
    }

    protected void setCalculatedFormula(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("calculatedFormula", "urn:tooling.soap.sforce.com","calculatedFormula","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setCalculatedFormula(__typeMapper.readString(__in, _lookupTypeInfo("calculatedFormula", "urn:tooling.soap.sforce.com","calculatedFormula","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldCalculatedFormula(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("calculatedFormula", "urn:tooling.soap.sforce.com","calculatedFormula","http://www.w3.org/2001/XMLSchema","string",0,1,true), calculatedFormula, calculatedFormula__is_set);
    }

    /**
     * element : cascadeDelete of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean cascadeDelete__is_set = false;

    private boolean cascadeDelete;

    public boolean getCascadeDelete() {
      return cascadeDelete;
    }

    public boolean isCascadeDelete() {
      return cascadeDelete;
    }

    public void setCascadeDelete(boolean cascadeDelete) {
      this.cascadeDelete = cascadeDelete;
      cascadeDelete__is_set = true;
    }

    protected void setCascadeDelete(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("cascadeDelete", "urn:tooling.soap.sforce.com","cascadeDelete","http://www.w3.org/2001/XMLSchema","boolean",0,1,true))) {
        setCascadeDelete(__typeMapper.readBoolean(__in, _lookupTypeInfo("cascadeDelete", "urn:tooling.soap.sforce.com","cascadeDelete","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), boolean.class));
      }
    }

    private void writeFieldCascadeDelete(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("cascadeDelete", "urn:tooling.soap.sforce.com","cascadeDelete","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), cascadeDelete, cascadeDelete__is_set);
    }

    /**
     * element : caseSensitive of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean caseSensitive__is_set = false;

    private boolean caseSensitive;

    public boolean getCaseSensitive() {
      return caseSensitive;
    }

    public boolean isCaseSensitive() {
      return caseSensitive;
    }

    public void setCaseSensitive(boolean caseSensitive) {
      this.caseSensitive = caseSensitive;
      caseSensitive__is_set = true;
    }

    protected void setCaseSensitive(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("caseSensitive", "urn:tooling.soap.sforce.com","caseSensitive","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setCaseSensitive(__typeMapper.readBoolean(__in, _lookupTypeInfo("caseSensitive", "urn:tooling.soap.sforce.com","caseSensitive","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldCaseSensitive(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("caseSensitive", "urn:tooling.soap.sforce.com","caseSensitive","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), caseSensitive, caseSensitive__is_set);
    }

    /**
     * element : compoundFieldName of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean compoundFieldName__is_set = false;

    private java.lang.String compoundFieldName;

    public java.lang.String getCompoundFieldName() {
      return compoundFieldName;
    }

    public void setCompoundFieldName(java.lang.String compoundFieldName) {
      this.compoundFieldName = compoundFieldName;
      compoundFieldName__is_set = true;
    }

    protected void setCompoundFieldName(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("compoundFieldName", "urn:tooling.soap.sforce.com","compoundFieldName","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setCompoundFieldName(__typeMapper.readString(__in, _lookupTypeInfo("compoundFieldName", "urn:tooling.soap.sforce.com","compoundFieldName","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldCompoundFieldName(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("compoundFieldName", "urn:tooling.soap.sforce.com","compoundFieldName","http://www.w3.org/2001/XMLSchema","string",0,1,true), compoundFieldName, compoundFieldName__is_set);
    }

    /**
     * element : controllerName of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean controllerName__is_set = false;

    private java.lang.String controllerName;

    public java.lang.String getControllerName() {
      return controllerName;
    }

    public void setControllerName(java.lang.String controllerName) {
      this.controllerName = controllerName;
      controllerName__is_set = true;
    }

    protected void setControllerName(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("controllerName", "urn:tooling.soap.sforce.com","controllerName","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setControllerName(__typeMapper.readString(__in, _lookupTypeInfo("controllerName", "urn:tooling.soap.sforce.com","controllerName","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldControllerName(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("controllerName", "urn:tooling.soap.sforce.com","controllerName","http://www.w3.org/2001/XMLSchema","string",0,1,true), controllerName, controllerName__is_set);
    }

    /**
     * element : createable of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean createable__is_set = false;

    private boolean createable;

    public boolean getCreateable() {
      return createable;
    }

    public boolean isCreateable() {
      return createable;
    }

    public void setCreateable(boolean createable) {
      this.createable = createable;
      createable__is_set = true;
    }

    protected void setCreateable(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("createable", "urn:tooling.soap.sforce.com","createable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setCreateable(__typeMapper.readBoolean(__in, _lookupTypeInfo("createable", "urn:tooling.soap.sforce.com","createable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldCreateable(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("createable", "urn:tooling.soap.sforce.com","createable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), createable, createable__is_set);
    }

    /**
     * element : custom of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean custom__is_set = false;

    private boolean custom;

    public boolean getCustom() {
      return custom;
    }

    public boolean isCustom() {
      return custom;
    }

    public void setCustom(boolean custom) {
      this.custom = custom;
      custom__is_set = true;
    }

    protected void setCustom(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("custom", "urn:tooling.soap.sforce.com","custom","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setCustom(__typeMapper.readBoolean(__in, _lookupTypeInfo("custom", "urn:tooling.soap.sforce.com","custom","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldCustom(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("custom", "urn:tooling.soap.sforce.com","custom","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), custom, custom__is_set);
    }

    /**
     * element : defaultValue of type {http://www.w3.org/2001/XMLSchema}anyType
     * java type: java.lang.Object
     */
    private boolean defaultValue__is_set = false;

    private java.lang.Object defaultValue;

    public java.lang.Object getDefaultValue() {
      return defaultValue;
    }

    public void setDefaultValue(java.lang.Object defaultValue) {
      this.defaultValue = defaultValue;
      defaultValue__is_set = true;
    }

    protected void setDefaultValue(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("defaultValue", "urn:tooling.soap.sforce.com","defaultValue","http://www.w3.org/2001/XMLSchema","anyType",0,1,true))) {
        setDefaultValue((java.lang.Object)__typeMapper.readObject(__in, _lookupTypeInfo("defaultValue", "urn:tooling.soap.sforce.com","defaultValue","http://www.w3.org/2001/XMLSchema","anyType",0,1,true), java.lang.Object.class));
      }
    }

    private void writeFieldDefaultValue(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("defaultValue", "urn:tooling.soap.sforce.com","defaultValue","http://www.w3.org/2001/XMLSchema","anyType",0,1,true), defaultValue, defaultValue__is_set);
    }

    /**
     * element : defaultValueFormula of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean defaultValueFormula__is_set = false;

    private java.lang.String defaultValueFormula;

    public java.lang.String getDefaultValueFormula() {
      return defaultValueFormula;
    }

    public void setDefaultValueFormula(java.lang.String defaultValueFormula) {
      this.defaultValueFormula = defaultValueFormula;
      defaultValueFormula__is_set = true;
    }

    protected void setDefaultValueFormula(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("defaultValueFormula", "urn:tooling.soap.sforce.com","defaultValueFormula","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setDefaultValueFormula(__typeMapper.readString(__in, _lookupTypeInfo("defaultValueFormula", "urn:tooling.soap.sforce.com","defaultValueFormula","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldDefaultValueFormula(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("defaultValueFormula", "urn:tooling.soap.sforce.com","defaultValueFormula","http://www.w3.org/2001/XMLSchema","string",0,1,true), defaultValueFormula, defaultValueFormula__is_set);
    }

    /**
     * element : defaultedOnCreate of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean defaultedOnCreate__is_set = false;

    private boolean defaultedOnCreate;

    public boolean getDefaultedOnCreate() {
      return defaultedOnCreate;
    }

    public boolean isDefaultedOnCreate() {
      return defaultedOnCreate;
    }

    public void setDefaultedOnCreate(boolean defaultedOnCreate) {
      this.defaultedOnCreate = defaultedOnCreate;
      defaultedOnCreate__is_set = true;
    }

    protected void setDefaultedOnCreate(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("defaultedOnCreate", "urn:tooling.soap.sforce.com","defaultedOnCreate","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setDefaultedOnCreate(__typeMapper.readBoolean(__in, _lookupTypeInfo("defaultedOnCreate", "urn:tooling.soap.sforce.com","defaultedOnCreate","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldDefaultedOnCreate(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("defaultedOnCreate", "urn:tooling.soap.sforce.com","defaultedOnCreate","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), defaultedOnCreate, defaultedOnCreate__is_set);
    }

    /**
     * element : dependentPicklist of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean dependentPicklist__is_set = false;

    private boolean dependentPicklist;

    public boolean getDependentPicklist() {
      return dependentPicklist;
    }

    public boolean isDependentPicklist() {
      return dependentPicklist;
    }

    public void setDependentPicklist(boolean dependentPicklist) {
      this.dependentPicklist = dependentPicklist;
      dependentPicklist__is_set = true;
    }

    protected void setDependentPicklist(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("dependentPicklist", "urn:tooling.soap.sforce.com","dependentPicklist","http://www.w3.org/2001/XMLSchema","boolean",0,1,true))) {
        setDependentPicklist(__typeMapper.readBoolean(__in, _lookupTypeInfo("dependentPicklist", "urn:tooling.soap.sforce.com","dependentPicklist","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), boolean.class));
      }
    }

    private void writeFieldDependentPicklist(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("dependentPicklist", "urn:tooling.soap.sforce.com","dependentPicklist","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), dependentPicklist, dependentPicklist__is_set);
    }

    /**
     * element : deprecatedAndHidden of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean deprecatedAndHidden__is_set = false;

    private boolean deprecatedAndHidden;

    public boolean getDeprecatedAndHidden() {
      return deprecatedAndHidden;
    }

    public boolean isDeprecatedAndHidden() {
      return deprecatedAndHidden;
    }

    public void setDeprecatedAndHidden(boolean deprecatedAndHidden) {
      this.deprecatedAndHidden = deprecatedAndHidden;
      deprecatedAndHidden__is_set = true;
    }

    protected void setDeprecatedAndHidden(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("deprecatedAndHidden", "urn:tooling.soap.sforce.com","deprecatedAndHidden","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setDeprecatedAndHidden(__typeMapper.readBoolean(__in, _lookupTypeInfo("deprecatedAndHidden", "urn:tooling.soap.sforce.com","deprecatedAndHidden","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldDeprecatedAndHidden(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("deprecatedAndHidden", "urn:tooling.soap.sforce.com","deprecatedAndHidden","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), deprecatedAndHidden, deprecatedAndHidden__is_set);
    }

    /**
     * element : digits of type {http://www.w3.org/2001/XMLSchema}int
     * java type: int
     */
    private boolean digits__is_set = false;

    private int digits;

    public int getDigits() {
      return digits;
    }

    public void setDigits(int digits) {
      this.digits = digits;
      digits__is_set = true;
    }

    protected void setDigits(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("digits", "urn:tooling.soap.sforce.com","digits","http://www.w3.org/2001/XMLSchema","int",1,1,true))) {
        setDigits((int)__typeMapper.readInt(__in, _lookupTypeInfo("digits", "urn:tooling.soap.sforce.com","digits","http://www.w3.org/2001/XMLSchema","int",1,1,true), int.class));
      }
    }

    private void writeFieldDigits(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("digits", "urn:tooling.soap.sforce.com","digits","http://www.w3.org/2001/XMLSchema","int",1,1,true), digits, digits__is_set);
    }

    /**
     * element : displayLocationInDecimal of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean displayLocationInDecimal__is_set = false;

    private boolean displayLocationInDecimal;

    public boolean getDisplayLocationInDecimal() {
      return displayLocationInDecimal;
    }

    public boolean isDisplayLocationInDecimal() {
      return displayLocationInDecimal;
    }

    public void setDisplayLocationInDecimal(boolean displayLocationInDecimal) {
      this.displayLocationInDecimal = displayLocationInDecimal;
      displayLocationInDecimal__is_set = true;
    }

    protected void setDisplayLocationInDecimal(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("displayLocationInDecimal", "urn:tooling.soap.sforce.com","displayLocationInDecimal","http://www.w3.org/2001/XMLSchema","boolean",0,1,true))) {
        setDisplayLocationInDecimal(__typeMapper.readBoolean(__in, _lookupTypeInfo("displayLocationInDecimal", "urn:tooling.soap.sforce.com","displayLocationInDecimal","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), boolean.class));
      }
    }

    private void writeFieldDisplayLocationInDecimal(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("displayLocationInDecimal", "urn:tooling.soap.sforce.com","displayLocationInDecimal","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), displayLocationInDecimal, displayLocationInDecimal__is_set);
    }

    /**
     * element : encrypted of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean encrypted__is_set = false;

    private boolean encrypted;

    public boolean getEncrypted() {
      return encrypted;
    }

    public boolean isEncrypted() {
      return encrypted;
    }

    public void setEncrypted(boolean encrypted) {
      this.encrypted = encrypted;
      encrypted__is_set = true;
    }

    protected void setEncrypted(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("encrypted", "urn:tooling.soap.sforce.com","encrypted","http://www.w3.org/2001/XMLSchema","boolean",0,1,true))) {
        setEncrypted(__typeMapper.readBoolean(__in, _lookupTypeInfo("encrypted", "urn:tooling.soap.sforce.com","encrypted","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), boolean.class));
      }
    }

    private void writeFieldEncrypted(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("encrypted", "urn:tooling.soap.sforce.com","encrypted","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), encrypted, encrypted__is_set);
    }

    /**
     * element : externalId of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean externalId__is_set = false;

    private boolean externalId;

    public boolean getExternalId() {
      return externalId;
    }

    public boolean isExternalId() {
      return externalId;
    }

    public void setExternalId(boolean externalId) {
      this.externalId = externalId;
      externalId__is_set = true;
    }

    protected void setExternalId(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("externalId", "urn:tooling.soap.sforce.com","externalId","http://www.w3.org/2001/XMLSchema","boolean",0,1,true))) {
        setExternalId(__typeMapper.readBoolean(__in, _lookupTypeInfo("externalId", "urn:tooling.soap.sforce.com","externalId","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), boolean.class));
      }
    }

    private void writeFieldExternalId(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("externalId", "urn:tooling.soap.sforce.com","externalId","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), externalId, externalId__is_set);
    }

    /**
     * element : extraTypeInfo of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean extraTypeInfo__is_set = false;

    private java.lang.String extraTypeInfo;

    public java.lang.String getExtraTypeInfo() {
      return extraTypeInfo;
    }

    public void setExtraTypeInfo(java.lang.String extraTypeInfo) {
      this.extraTypeInfo = extraTypeInfo;
      extraTypeInfo__is_set = true;
    }

    protected void setExtraTypeInfo(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("extraTypeInfo", "urn:tooling.soap.sforce.com","extraTypeInfo","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setExtraTypeInfo(__typeMapper.readString(__in, _lookupTypeInfo("extraTypeInfo", "urn:tooling.soap.sforce.com","extraTypeInfo","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldExtraTypeInfo(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("extraTypeInfo", "urn:tooling.soap.sforce.com","extraTypeInfo","http://www.w3.org/2001/XMLSchema","string",0,1,true), extraTypeInfo, extraTypeInfo__is_set);
    }

    /**
     * element : filterable of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean filterable__is_set = false;

    private boolean filterable;

    public boolean getFilterable() {
      return filterable;
    }

    public boolean isFilterable() {
      return filterable;
    }

    public void setFilterable(boolean filterable) {
      this.filterable = filterable;
      filterable__is_set = true;
    }

    protected void setFilterable(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("filterable", "urn:tooling.soap.sforce.com","filterable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setFilterable(__typeMapper.readBoolean(__in, _lookupTypeInfo("filterable", "urn:tooling.soap.sforce.com","filterable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldFilterable(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("filterable", "urn:tooling.soap.sforce.com","filterable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), filterable, filterable__is_set);
    }

    /**
     * element : filteredLookupInfo of type {urn:tooling.soap.sforce.com}FilteredLookupInfo
     * java type: com.sforce.soap.tooling.FilteredLookupInfo
     */
    private boolean filteredLookupInfo__is_set = false;

    private com.sforce.soap.tooling.FilteredLookupInfo filteredLookupInfo;

    public com.sforce.soap.tooling.FilteredLookupInfo getFilteredLookupInfo() {
      return filteredLookupInfo;
    }

    public void setFilteredLookupInfo(com.sforce.soap.tooling.FilteredLookupInfo filteredLookupInfo) {
      this.filteredLookupInfo = filteredLookupInfo;
      filteredLookupInfo__is_set = true;
    }

    protected void setFilteredLookupInfo(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("filteredLookupInfo", "urn:tooling.soap.sforce.com","filteredLookupInfo","urn:tooling.soap.sforce.com","FilteredLookupInfo",0,1,true))) {
        setFilteredLookupInfo((com.sforce.soap.tooling.FilteredLookupInfo)__typeMapper.readObject(__in, _lookupTypeInfo("filteredLookupInfo", "urn:tooling.soap.sforce.com","filteredLookupInfo","urn:tooling.soap.sforce.com","FilteredLookupInfo",0,1,true), com.sforce.soap.tooling.FilteredLookupInfo.class));
      }
    }

    private void writeFieldFilteredLookupInfo(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("filteredLookupInfo", "urn:tooling.soap.sforce.com","filteredLookupInfo","urn:tooling.soap.sforce.com","FilteredLookupInfo",0,1,true), filteredLookupInfo, filteredLookupInfo__is_set);
    }

    /**
     * element : formulaTreatNullNumberAsZero of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean formulaTreatNullNumberAsZero__is_set = false;

    private boolean formulaTreatNullNumberAsZero;

    public boolean getFormulaTreatNullNumberAsZero() {
      return formulaTreatNullNumberAsZero;
    }

    public boolean isFormulaTreatNullNumberAsZero() {
      return formulaTreatNullNumberAsZero;
    }

    public void setFormulaTreatNullNumberAsZero(boolean formulaTreatNullNumberAsZero) {
      this.formulaTreatNullNumberAsZero = formulaTreatNullNumberAsZero;
      formulaTreatNullNumberAsZero__is_set = true;
    }

    protected void setFormulaTreatNullNumberAsZero(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("formulaTreatNullNumberAsZero", "urn:tooling.soap.sforce.com","formulaTreatNullNumberAsZero","http://www.w3.org/2001/XMLSchema","boolean",0,1,true))) {
        setFormulaTreatNullNumberAsZero(__typeMapper.readBoolean(__in, _lookupTypeInfo("formulaTreatNullNumberAsZero", "urn:tooling.soap.sforce.com","formulaTreatNullNumberAsZero","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), boolean.class));
      }
    }

    private void writeFieldFormulaTreatNullNumberAsZero(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("formulaTreatNullNumberAsZero", "urn:tooling.soap.sforce.com","formulaTreatNullNumberAsZero","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), formulaTreatNullNumberAsZero, formulaTreatNullNumberAsZero__is_set);
    }

    /**
     * element : groupable of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean groupable__is_set = false;

    private boolean groupable;

    public boolean getGroupable() {
      return groupable;
    }

    public boolean isGroupable() {
      return groupable;
    }

    public void setGroupable(boolean groupable) {
      this.groupable = groupable;
      groupable__is_set = true;
    }

    protected void setGroupable(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("groupable", "urn:tooling.soap.sforce.com","groupable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setGroupable(__typeMapper.readBoolean(__in, _lookupTypeInfo("groupable", "urn:tooling.soap.sforce.com","groupable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldGroupable(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("groupable", "urn:tooling.soap.sforce.com","groupable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), groupable, groupable__is_set);
    }

    /**
     * element : highScaleNumber of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean highScaleNumber__is_set = false;

    private boolean highScaleNumber;

    public boolean getHighScaleNumber() {
      return highScaleNumber;
    }

    public boolean isHighScaleNumber() {
      return highScaleNumber;
    }

    public void setHighScaleNumber(boolean highScaleNumber) {
      this.highScaleNumber = highScaleNumber;
      highScaleNumber__is_set = true;
    }

    protected void setHighScaleNumber(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("highScaleNumber", "urn:tooling.soap.sforce.com","highScaleNumber","http://www.w3.org/2001/XMLSchema","boolean",0,1,true))) {
        setHighScaleNumber(__typeMapper.readBoolean(__in, _lookupTypeInfo("highScaleNumber", "urn:tooling.soap.sforce.com","highScaleNumber","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), boolean.class));
      }
    }

    private void writeFieldHighScaleNumber(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("highScaleNumber", "urn:tooling.soap.sforce.com","highScaleNumber","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), highScaleNumber, highScaleNumber__is_set);
    }

    /**
     * element : htmlFormatted of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean htmlFormatted__is_set = false;

    private boolean htmlFormatted;

    public boolean getHtmlFormatted() {
      return htmlFormatted;
    }

    public boolean isHtmlFormatted() {
      return htmlFormatted;
    }

    public void setHtmlFormatted(boolean htmlFormatted) {
      this.htmlFormatted = htmlFormatted;
      htmlFormatted__is_set = true;
    }

    protected void setHtmlFormatted(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("htmlFormatted", "urn:tooling.soap.sforce.com","htmlFormatted","http://www.w3.org/2001/XMLSchema","boolean",0,1,true))) {
        setHtmlFormatted(__typeMapper.readBoolean(__in, _lookupTypeInfo("htmlFormatted", "urn:tooling.soap.sforce.com","htmlFormatted","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), boolean.class));
      }
    }

    private void writeFieldHtmlFormatted(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("htmlFormatted", "urn:tooling.soap.sforce.com","htmlFormatted","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), htmlFormatted, htmlFormatted__is_set);
    }

    /**
     * element : idLookup of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean idLookup__is_set = false;

    private boolean idLookup;

    public boolean getIdLookup() {
      return idLookup;
    }

    public boolean isIdLookup() {
      return idLookup;
    }

    public void setIdLookup(boolean idLookup) {
      this.idLookup = idLookup;
      idLookup__is_set = true;
    }

    protected void setIdLookup(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("idLookup", "urn:tooling.soap.sforce.com","idLookup","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setIdLookup(__typeMapper.readBoolean(__in, _lookupTypeInfo("idLookup", "urn:tooling.soap.sforce.com","idLookup","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldIdLookup(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("idLookup", "urn:tooling.soap.sforce.com","idLookup","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), idLookup, idLookup__is_set);
    }

    /**
     * element : inlineHelpText of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean inlineHelpText__is_set = false;

    private java.lang.String inlineHelpText;

    public java.lang.String getInlineHelpText() {
      return inlineHelpText;
    }

    public void setInlineHelpText(java.lang.String inlineHelpText) {
      this.inlineHelpText = inlineHelpText;
      inlineHelpText__is_set = true;
    }

    protected void setInlineHelpText(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("inlineHelpText", "urn:tooling.soap.sforce.com","inlineHelpText","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setInlineHelpText(__typeMapper.readString(__in, _lookupTypeInfo("inlineHelpText", "urn:tooling.soap.sforce.com","inlineHelpText","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldInlineHelpText(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("inlineHelpText", "urn:tooling.soap.sforce.com","inlineHelpText","http://www.w3.org/2001/XMLSchema","string",0,1,true), inlineHelpText, inlineHelpText__is_set);
    }

    /**
     * element : label of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean label__is_set = false;

    private java.lang.String label;

    public java.lang.String getLabel() {
      return label;
    }

    public void setLabel(java.lang.String label) {
      this.label = label;
      label__is_set = true;
    }

    protected void setLabel(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("label", "urn:tooling.soap.sforce.com","label","http://www.w3.org/2001/XMLSchema","string",1,1,true))) {
        setLabel(__typeMapper.readString(__in, _lookupTypeInfo("label", "urn:tooling.soap.sforce.com","label","http://www.w3.org/2001/XMLSchema","string",1,1,true), java.lang.String.class));
      }
    }

    private void writeFieldLabel(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("label", "urn:tooling.soap.sforce.com","label","http://www.w3.org/2001/XMLSchema","string",1,1,true), label, label__is_set);
    }

    /**
     * element : length of type {http://www.w3.org/2001/XMLSchema}int
     * java type: int
     */
    private boolean length__is_set = false;

    private int length;

    public int getLength() {
      return length;
    }

    public void setLength(int length) {
      this.length = length;
      length__is_set = true;
    }

    protected void setLength(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("length", "urn:tooling.soap.sforce.com","length","http://www.w3.org/2001/XMLSchema","int",1,1,true))) {
        setLength((int)__typeMapper.readInt(__in, _lookupTypeInfo("length", "urn:tooling.soap.sforce.com","length","http://www.w3.org/2001/XMLSchema","int",1,1,true), int.class));
      }
    }

    private void writeFieldLength(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("length", "urn:tooling.soap.sforce.com","length","http://www.w3.org/2001/XMLSchema","int",1,1,true), length, length__is_set);
    }

    /**
     * element : mask of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean mask__is_set = false;

    private java.lang.String mask;

    public java.lang.String getMask() {
      return mask;
    }

    public void setMask(java.lang.String mask) {
      this.mask = mask;
      mask__is_set = true;
    }

    protected void setMask(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("mask", "urn:tooling.soap.sforce.com","mask","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setMask(__typeMapper.readString(__in, _lookupTypeInfo("mask", "urn:tooling.soap.sforce.com","mask","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldMask(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("mask", "urn:tooling.soap.sforce.com","mask","http://www.w3.org/2001/XMLSchema","string",0,1,true), mask, mask__is_set);
    }

    /**
     * element : maskType of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean maskType__is_set = false;

    private java.lang.String maskType;

    public java.lang.String getMaskType() {
      return maskType;
    }

    public void setMaskType(java.lang.String maskType) {
      this.maskType = maskType;
      maskType__is_set = true;
    }

    protected void setMaskType(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("maskType", "urn:tooling.soap.sforce.com","maskType","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setMaskType(__typeMapper.readString(__in, _lookupTypeInfo("maskType", "urn:tooling.soap.sforce.com","maskType","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldMaskType(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("maskType", "urn:tooling.soap.sforce.com","maskType","http://www.w3.org/2001/XMLSchema","string",0,1,true), maskType, maskType__is_set);
    }

    /**
     * element : name of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean name__is_set = false;

    private java.lang.String name;

    public java.lang.String getName() {
      return name;
    }

    public void setName(java.lang.String name) {
      this.name = name;
      name__is_set = true;
    }

    protected void setName(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("name", "urn:tooling.soap.sforce.com","name","http://www.w3.org/2001/XMLSchema","string",1,1,true))) {
        setName(__typeMapper.readString(__in, _lookupTypeInfo("name", "urn:tooling.soap.sforce.com","name","http://www.w3.org/2001/XMLSchema","string",1,1,true), java.lang.String.class));
      }
    }

    private void writeFieldName(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("name", "urn:tooling.soap.sforce.com","name","http://www.w3.org/2001/XMLSchema","string",1,1,true), name, name__is_set);
    }

    /**
     * element : nameField of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean nameField__is_set = false;

    private boolean nameField;

    public boolean getNameField() {
      return nameField;
    }

    public boolean isNameField() {
      return nameField;
    }

    public void setNameField(boolean nameField) {
      this.nameField = nameField;
      nameField__is_set = true;
    }

    protected void setNameField(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("nameField", "urn:tooling.soap.sforce.com","nameField","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setNameField(__typeMapper.readBoolean(__in, _lookupTypeInfo("nameField", "urn:tooling.soap.sforce.com","nameField","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldNameField(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("nameField", "urn:tooling.soap.sforce.com","nameField","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), nameField, nameField__is_set);
    }

    /**
     * element : namePointing of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean namePointing__is_set = false;

    private boolean namePointing;

    public boolean getNamePointing() {
      return namePointing;
    }

    public boolean isNamePointing() {
      return namePointing;
    }

    public void setNamePointing(boolean namePointing) {
      this.namePointing = namePointing;
      namePointing__is_set = true;
    }

    protected void setNamePointing(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("namePointing", "urn:tooling.soap.sforce.com","namePointing","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setNamePointing(__typeMapper.readBoolean(__in, _lookupTypeInfo("namePointing", "urn:tooling.soap.sforce.com","namePointing","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldNamePointing(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("namePointing", "urn:tooling.soap.sforce.com","namePointing","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), namePointing, namePointing__is_set);
    }

    /**
     * element : nillable of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean nillable__is_set = false;

    private boolean nillable;

    public boolean getNillable() {
      return nillable;
    }

    public boolean isNillable() {
      return nillable;
    }

    public void setNillable(boolean nillable) {
      this.nillable = nillable;
      nillable__is_set = true;
    }

    protected void setNillable(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("nillable", "urn:tooling.soap.sforce.com","nillable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setNillable(__typeMapper.readBoolean(__in, _lookupTypeInfo("nillable", "urn:tooling.soap.sforce.com","nillable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldNillable(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("nillable", "urn:tooling.soap.sforce.com","nillable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), nillable, nillable__is_set);
    }

    /**
     * element : permissionable of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean permissionable__is_set = false;

    private boolean permissionable;

    public boolean getPermissionable() {
      return permissionable;
    }

    public boolean isPermissionable() {
      return permissionable;
    }

    public void setPermissionable(boolean permissionable) {
      this.permissionable = permissionable;
      permissionable__is_set = true;
    }

    protected void setPermissionable(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("permissionable", "urn:tooling.soap.sforce.com","permissionable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setPermissionable(__typeMapper.readBoolean(__in, _lookupTypeInfo("permissionable", "urn:tooling.soap.sforce.com","permissionable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldPermissionable(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("permissionable", "urn:tooling.soap.sforce.com","permissionable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), permissionable, permissionable__is_set);
    }

    /**
     * element : picklistValues of type {urn:tooling.soap.sforce.com}PicklistEntry
     * java type: com.sforce.soap.tooling.PicklistEntry[]
     */
    private boolean picklistValues__is_set = false;

    private com.sforce.soap.tooling.PicklistEntry[] picklistValues = new com.sforce.soap.tooling.PicklistEntry[0];

    public com.sforce.soap.tooling.PicklistEntry[] getPicklistValues() {
      return picklistValues;
    }

    public void setPicklistValues(com.sforce.soap.tooling.PicklistEntry[] picklistValues) {
      this.picklistValues = picklistValues;
      picklistValues__is_set = true;
    }

    protected void setPicklistValues(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("picklistValues", "urn:tooling.soap.sforce.com","picklistValues","urn:tooling.soap.sforce.com","PicklistEntry",0,-1,true))) {
        setPicklistValues((com.sforce.soap.tooling.PicklistEntry[])__typeMapper.readObject(__in, _lookupTypeInfo("picklistValues", "urn:tooling.soap.sforce.com","picklistValues","urn:tooling.soap.sforce.com","PicklistEntry",0,-1,true), com.sforce.soap.tooling.PicklistEntry[].class));
      }
    }

    private void writeFieldPicklistValues(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("picklistValues", "urn:tooling.soap.sforce.com","picklistValues","urn:tooling.soap.sforce.com","PicklistEntry",0,-1,true), picklistValues, picklistValues__is_set);
    }

    /**
     * element : polymorphicForeignKey of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean polymorphicForeignKey__is_set = false;

    private boolean polymorphicForeignKey;

    public boolean getPolymorphicForeignKey() {
      return polymorphicForeignKey;
    }

    public boolean isPolymorphicForeignKey() {
      return polymorphicForeignKey;
    }

    public void setPolymorphicForeignKey(boolean polymorphicForeignKey) {
      this.polymorphicForeignKey = polymorphicForeignKey;
      polymorphicForeignKey__is_set = true;
    }

    protected void setPolymorphicForeignKey(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("polymorphicForeignKey", "urn:tooling.soap.sforce.com","polymorphicForeignKey","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setPolymorphicForeignKey(__typeMapper.readBoolean(__in, _lookupTypeInfo("polymorphicForeignKey", "urn:tooling.soap.sforce.com","polymorphicForeignKey","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldPolymorphicForeignKey(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("polymorphicForeignKey", "urn:tooling.soap.sforce.com","polymorphicForeignKey","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), polymorphicForeignKey, polymorphicForeignKey__is_set);
    }

    /**
     * element : precision of type {http://www.w3.org/2001/XMLSchema}int
     * java type: int
     */
    private boolean precision__is_set = false;

    private int precision;

    public int getPrecision() {
      return precision;
    }

    public void setPrecision(int precision) {
      this.precision = precision;
      precision__is_set = true;
    }

    protected void setPrecision(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("precision", "urn:tooling.soap.sforce.com","precision","http://www.w3.org/2001/XMLSchema","int",1,1,true))) {
        setPrecision((int)__typeMapper.readInt(__in, _lookupTypeInfo("precision", "urn:tooling.soap.sforce.com","precision","http://www.w3.org/2001/XMLSchema","int",1,1,true), int.class));
      }
    }

    private void writeFieldPrecision(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("precision", "urn:tooling.soap.sforce.com","precision","http://www.w3.org/2001/XMLSchema","int",1,1,true), precision, precision__is_set);
    }

    /**
     * element : referenceTargetField of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean referenceTargetField__is_set = false;

    private java.lang.String referenceTargetField;

    public java.lang.String getReferenceTargetField() {
      return referenceTargetField;
    }

    public void setReferenceTargetField(java.lang.String referenceTargetField) {
      this.referenceTargetField = referenceTargetField;
      referenceTargetField__is_set = true;
    }

    protected void setReferenceTargetField(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("referenceTargetField", "urn:tooling.soap.sforce.com","referenceTargetField","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setReferenceTargetField(__typeMapper.readString(__in, _lookupTypeInfo("referenceTargetField", "urn:tooling.soap.sforce.com","referenceTargetField","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldReferenceTargetField(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("referenceTargetField", "urn:tooling.soap.sforce.com","referenceTargetField","http://www.w3.org/2001/XMLSchema","string",0,1,true), referenceTargetField, referenceTargetField__is_set);
    }

    /**
     * element : referenceTo of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String[]
     */
    private boolean referenceTo__is_set = false;

    private java.lang.String[] referenceTo = new java.lang.String[0];

    public java.lang.String[] getReferenceTo() {
      return referenceTo;
    }

    public void setReferenceTo(java.lang.String[] referenceTo) {
      this.referenceTo = referenceTo;
      referenceTo__is_set = true;
    }

    protected void setReferenceTo(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("referenceTo", "urn:tooling.soap.sforce.com","referenceTo","http://www.w3.org/2001/XMLSchema","string",0,-1,true))) {
        setReferenceTo((java.lang.String[])__typeMapper.readObject(__in, _lookupTypeInfo("referenceTo", "urn:tooling.soap.sforce.com","referenceTo","http://www.w3.org/2001/XMLSchema","string",0,-1,true), java.lang.String[].class));
      }
    }

    private void writeFieldReferenceTo(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("referenceTo", "urn:tooling.soap.sforce.com","referenceTo","http://www.w3.org/2001/XMLSchema","string",0,-1,true), referenceTo, referenceTo__is_set);
    }

    /**
     * element : relationshipName of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean relationshipName__is_set = false;

    private java.lang.String relationshipName;

    public java.lang.String getRelationshipName() {
      return relationshipName;
    }

    public void setRelationshipName(java.lang.String relationshipName) {
      this.relationshipName = relationshipName;
      relationshipName__is_set = true;
    }

    protected void setRelationshipName(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("relationshipName", "urn:tooling.soap.sforce.com","relationshipName","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setRelationshipName(__typeMapper.readString(__in, _lookupTypeInfo("relationshipName", "urn:tooling.soap.sforce.com","relationshipName","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldRelationshipName(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("relationshipName", "urn:tooling.soap.sforce.com","relationshipName","http://www.w3.org/2001/XMLSchema","string",0,1,true), relationshipName, relationshipName__is_set);
    }

    /**
     * element : relationshipOrder of type {http://www.w3.org/2001/XMLSchema}int
     * java type: int
     */
    private boolean relationshipOrder__is_set = false;

    private int relationshipOrder;

    public int getRelationshipOrder() {
      return relationshipOrder;
    }

    public void setRelationshipOrder(int relationshipOrder) {
      this.relationshipOrder = relationshipOrder;
      relationshipOrder__is_set = true;
    }

    protected void setRelationshipOrder(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("relationshipOrder", "urn:tooling.soap.sforce.com","relationshipOrder","http://www.w3.org/2001/XMLSchema","int",0,1,true))) {
        setRelationshipOrder((int)__typeMapper.readInt(__in, _lookupTypeInfo("relationshipOrder", "urn:tooling.soap.sforce.com","relationshipOrder","http://www.w3.org/2001/XMLSchema","int",0,1,true), int.class));
      }
    }

    private void writeFieldRelationshipOrder(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("relationshipOrder", "urn:tooling.soap.sforce.com","relationshipOrder","http://www.w3.org/2001/XMLSchema","int",0,1,true), relationshipOrder, relationshipOrder__is_set);
    }

    /**
     * element : restrictedDelete of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean restrictedDelete__is_set = false;

    private boolean restrictedDelete;

    public boolean getRestrictedDelete() {
      return restrictedDelete;
    }

    public boolean isRestrictedDelete() {
      return restrictedDelete;
    }

    public void setRestrictedDelete(boolean restrictedDelete) {
      this.restrictedDelete = restrictedDelete;
      restrictedDelete__is_set = true;
    }

    protected void setRestrictedDelete(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("restrictedDelete", "urn:tooling.soap.sforce.com","restrictedDelete","http://www.w3.org/2001/XMLSchema","boolean",0,1,true))) {
        setRestrictedDelete(__typeMapper.readBoolean(__in, _lookupTypeInfo("restrictedDelete", "urn:tooling.soap.sforce.com","restrictedDelete","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), boolean.class));
      }
    }

    private void writeFieldRestrictedDelete(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("restrictedDelete", "urn:tooling.soap.sforce.com","restrictedDelete","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), restrictedDelete, restrictedDelete__is_set);
    }

    /**
     * element : restrictedPicklist of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean restrictedPicklist__is_set = false;

    private boolean restrictedPicklist;

    public boolean getRestrictedPicklist() {
      return restrictedPicklist;
    }

    public boolean isRestrictedPicklist() {
      return restrictedPicklist;
    }

    public void setRestrictedPicklist(boolean restrictedPicklist) {
      this.restrictedPicklist = restrictedPicklist;
      restrictedPicklist__is_set = true;
    }

    protected void setRestrictedPicklist(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("restrictedPicklist", "urn:tooling.soap.sforce.com","restrictedPicklist","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setRestrictedPicklist(__typeMapper.readBoolean(__in, _lookupTypeInfo("restrictedPicklist", "urn:tooling.soap.sforce.com","restrictedPicklist","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldRestrictedPicklist(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("restrictedPicklist", "urn:tooling.soap.sforce.com","restrictedPicklist","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), restrictedPicklist, restrictedPicklist__is_set);
    }

    /**
     * element : scale of type {http://www.w3.org/2001/XMLSchema}int
     * java type: int
     */
    private boolean scale__is_set = false;

    private int scale;

    public int getScale() {
      return scale;
    }

    public void setScale(int scale) {
      this.scale = scale;
      scale__is_set = true;
    }

    protected void setScale(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("scale", "urn:tooling.soap.sforce.com","scale","http://www.w3.org/2001/XMLSchema","int",1,1,true))) {
        setScale((int)__typeMapper.readInt(__in, _lookupTypeInfo("scale", "urn:tooling.soap.sforce.com","scale","http://www.w3.org/2001/XMLSchema","int",1,1,true), int.class));
      }
    }

    private void writeFieldScale(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("scale", "urn:tooling.soap.sforce.com","scale","http://www.w3.org/2001/XMLSchema","int",1,1,true), scale, scale__is_set);
    }

    /**
     * element : searchPrefilterable of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean searchPrefilterable__is_set = false;

    private boolean searchPrefilterable;

    public boolean getSearchPrefilterable() {
      return searchPrefilterable;
    }

    public boolean isSearchPrefilterable() {
      return searchPrefilterable;
    }

    public void setSearchPrefilterable(boolean searchPrefilterable) {
      this.searchPrefilterable = searchPrefilterable;
      searchPrefilterable__is_set = true;
    }

    protected void setSearchPrefilterable(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("searchPrefilterable", "urn:tooling.soap.sforce.com","searchPrefilterable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setSearchPrefilterable(__typeMapper.readBoolean(__in, _lookupTypeInfo("searchPrefilterable", "urn:tooling.soap.sforce.com","searchPrefilterable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldSearchPrefilterable(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("searchPrefilterable", "urn:tooling.soap.sforce.com","searchPrefilterable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), searchPrefilterable, searchPrefilterable__is_set);
    }

    /**
     * element : soapType of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean soapType__is_set = false;

    private java.lang.String soapType;

    public java.lang.String getSoapType() {
      return soapType;
    }

    public void setSoapType(java.lang.String soapType) {
      this.soapType = soapType;
      soapType__is_set = true;
    }

    protected void setSoapType(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("soapType", "urn:tooling.soap.sforce.com","soapType","http://www.w3.org/2001/XMLSchema","string",1,1,true))) {
        setSoapType(__typeMapper.readString(__in, _lookupTypeInfo("soapType", "urn:tooling.soap.sforce.com","soapType","http://www.w3.org/2001/XMLSchema","string",1,1,true), java.lang.String.class));
      }
    }

    private void writeFieldSoapType(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("soapType", "urn:tooling.soap.sforce.com","soapType","http://www.w3.org/2001/XMLSchema","string",1,1,true), soapType, soapType__is_set);
    }

    /**
     * element : sortable of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean sortable__is_set = false;

    private boolean sortable;

    public boolean getSortable() {
      return sortable;
    }

    public boolean isSortable() {
      return sortable;
    }

    public void setSortable(boolean sortable) {
      this.sortable = sortable;
      sortable__is_set = true;
    }

    protected void setSortable(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("sortable", "urn:tooling.soap.sforce.com","sortable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setSortable(__typeMapper.readBoolean(__in, _lookupTypeInfo("sortable", "urn:tooling.soap.sforce.com","sortable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldSortable(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("sortable", "urn:tooling.soap.sforce.com","sortable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), sortable, sortable__is_set);
    }

    /**
     * element : type of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean type__is_set = false;

    private java.lang.String type;

    public java.lang.String getType() {
      return type;
    }

    public void setType(java.lang.String type) {
      this.type = type;
      type__is_set = true;
    }

    protected void setType(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("type", "urn:tooling.soap.sforce.com","type","http://www.w3.org/2001/XMLSchema","string",1,1,true))) {
        setType(__typeMapper.readString(__in, _lookupTypeInfo("type", "urn:tooling.soap.sforce.com","type","http://www.w3.org/2001/XMLSchema","string",1,1,true), java.lang.String.class));
      }
    }

    private void writeFieldType(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("type", "urn:tooling.soap.sforce.com","type","http://www.w3.org/2001/XMLSchema","string",1,1,true), type, type__is_set);
    }

    /**
     * element : unique of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean unique__is_set = false;

    private boolean unique;

    public boolean getUnique() {
      return unique;
    }

    public boolean isUnique() {
      return unique;
    }

    public void setUnique(boolean unique) {
      this.unique = unique;
      unique__is_set = true;
    }

    protected void setUnique(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("unique", "urn:tooling.soap.sforce.com","unique","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setUnique(__typeMapper.readBoolean(__in, _lookupTypeInfo("unique", "urn:tooling.soap.sforce.com","unique","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldUnique(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("unique", "urn:tooling.soap.sforce.com","unique","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), unique, unique__is_set);
    }

    /**
     * element : updateable of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean updateable__is_set = false;

    private boolean updateable;

    public boolean getUpdateable() {
      return updateable;
    }

    public boolean isUpdateable() {
      return updateable;
    }

    public void setUpdateable(boolean updateable) {
      this.updateable = updateable;
      updateable__is_set = true;
    }

    protected void setUpdateable(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("updateable", "urn:tooling.soap.sforce.com","updateable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setUpdateable(__typeMapper.readBoolean(__in, _lookupTypeInfo("updateable", "urn:tooling.soap.sforce.com","updateable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldUpdateable(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("updateable", "urn:tooling.soap.sforce.com","updateable","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), updateable, updateable__is_set);
    }

    /**
     * element : writeRequiresMasterRead of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean writeRequiresMasterRead__is_set = false;

    private boolean writeRequiresMasterRead;

    public boolean getWriteRequiresMasterRead() {
      return writeRequiresMasterRead;
    }

    public boolean isWriteRequiresMasterRead() {
      return writeRequiresMasterRead;
    }

    public void setWriteRequiresMasterRead(boolean writeRequiresMasterRead) {
      this.writeRequiresMasterRead = writeRequiresMasterRead;
      writeRequiresMasterRead__is_set = true;
    }

    protected void setWriteRequiresMasterRead(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("writeRequiresMasterRead", "urn:tooling.soap.sforce.com","writeRequiresMasterRead","http://www.w3.org/2001/XMLSchema","boolean",0,1,true))) {
        setWriteRequiresMasterRead(__typeMapper.readBoolean(__in, _lookupTypeInfo("writeRequiresMasterRead", "urn:tooling.soap.sforce.com","writeRequiresMasterRead","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), boolean.class));
      }
    }

    private void writeFieldWriteRequiresMasterRead(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("writeRequiresMasterRead", "urn:tooling.soap.sforce.com","writeRequiresMasterRead","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), writeRequiresMasterRead, writeRequiresMasterRead__is_set);
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       writeFields1(__out, __typeMapper);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        loadFields1(__in, __typeMapper);
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[Field ");
      toString1(sb);

      sb.append("]\n");
      return sb.toString();
    }

    private void toStringHelper(StringBuilder sb, String name, Object value) {
      sb.append(' ').append(name).append("='").append(com.sforce.ws.util.Verbose.toString(value)).append("'\n");
    }

    private void writeFields1(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      writeFieldAggregatable(__out, __typeMapper);
      writeFieldAiPredictionField(__out, __typeMapper);
      writeFieldAutoNumber(__out, __typeMapper);
      writeFieldByteLength(__out, __typeMapper);
      writeFieldCalculated(__out, __typeMapper);
      writeFieldCalculatedFormula(__out, __typeMapper);
      writeFieldCascadeDelete(__out, __typeMapper);
      writeFieldCaseSensitive(__out, __typeMapper);
      writeFieldCompoundFieldName(__out, __typeMapper);
      writeFieldControllerName(__out, __typeMapper);
      writeFieldCreateable(__out, __typeMapper);
      writeFieldCustom(__out, __typeMapper);
      writeFieldDefaultValue(__out, __typeMapper);
      writeFieldDefaultValueFormula(__out, __typeMapper);
      writeFieldDefaultedOnCreate(__out, __typeMapper);
      writeFieldDependentPicklist(__out, __typeMapper);
      writeFieldDeprecatedAndHidden(__out, __typeMapper);
      writeFieldDigits(__out, __typeMapper);
      writeFieldDisplayLocationInDecimal(__out, __typeMapper);
      writeFieldEncrypted(__out, __typeMapper);
      writeFieldExternalId(__out, __typeMapper);
      writeFieldExtraTypeInfo(__out, __typeMapper);
      writeFieldFilterable(__out, __typeMapper);
      writeFieldFilteredLookupInfo(__out, __typeMapper);
      writeFieldFormulaTreatNullNumberAsZero(__out, __typeMapper);
      writeFieldGroupable(__out, __typeMapper);
      writeFieldHighScaleNumber(__out, __typeMapper);
      writeFieldHtmlFormatted(__out, __typeMapper);
      writeFieldIdLookup(__out, __typeMapper);
      writeFieldInlineHelpText(__out, __typeMapper);
      writeFieldLabel(__out, __typeMapper);
      writeFieldLength(__out, __typeMapper);
      writeFieldMask(__out, __typeMapper);
      writeFieldMaskType(__out, __typeMapper);
      writeFieldName(__out, __typeMapper);
      writeFieldNameField(__out, __typeMapper);
      writeFieldNamePointing(__out, __typeMapper);
      writeFieldNillable(__out, __typeMapper);
      writeFieldPermissionable(__out, __typeMapper);
      writeFieldPicklistValues(__out, __typeMapper);
      writeFieldPolymorphicForeignKey(__out, __typeMapper);
      writeFieldPrecision(__out, __typeMapper);
      writeFieldReferenceTargetField(__out, __typeMapper);
      writeFieldReferenceTo(__out, __typeMapper);
      writeFieldRelationshipName(__out, __typeMapper);
      writeFieldRelationshipOrder(__out, __typeMapper);
      writeFieldRestrictedDelete(__out, __typeMapper);
      writeFieldRestrictedPicklist(__out, __typeMapper);
      writeFieldScale(__out, __typeMapper);
      writeFieldSearchPrefilterable(__out, __typeMapper);
      writeFieldSoapType(__out, __typeMapper);
      writeFieldSortable(__out, __typeMapper);
      writeFieldType(__out, __typeMapper);
      writeFieldUnique(__out, __typeMapper);
      writeFieldUpdateable(__out, __typeMapper);
      writeFieldWriteRequiresMasterRead(__out, __typeMapper);
    }

    private void loadFields1(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      setAggregatable(__in, __typeMapper);
      setAiPredictionField(__in, __typeMapper);
      setAutoNumber(__in, __typeMapper);
      setByteLength(__in, __typeMapper);
      setCalculated(__in, __typeMapper);
      setCalculatedFormula(__in, __typeMapper);
      setCascadeDelete(__in, __typeMapper);
      setCaseSensitive(__in, __typeMapper);
      setCompoundFieldName(__in, __typeMapper);
      setControllerName(__in, __typeMapper);
      setCreateable(__in, __typeMapper);
      setCustom(__in, __typeMapper);
      setDefaultValue(__in, __typeMapper);
      setDefaultValueFormula(__in, __typeMapper);
      setDefaultedOnCreate(__in, __typeMapper);
      setDependentPicklist(__in, __typeMapper);
      setDeprecatedAndHidden(__in, __typeMapper);
      setDigits(__in, __typeMapper);
      setDisplayLocationInDecimal(__in, __typeMapper);
      setEncrypted(__in, __typeMapper);
      setExternalId(__in, __typeMapper);
      setExtraTypeInfo(__in, __typeMapper);
      setFilterable(__in, __typeMapper);
      setFilteredLookupInfo(__in, __typeMapper);
      setFormulaTreatNullNumberAsZero(__in, __typeMapper);
      setGroupable(__in, __typeMapper);
      setHighScaleNumber(__in, __typeMapper);
      setHtmlFormatted(__in, __typeMapper);
      setIdLookup(__in, __typeMapper);
      setInlineHelpText(__in, __typeMapper);
      setLabel(__in, __typeMapper);
      setLength(__in, __typeMapper);
      setMask(__in, __typeMapper);
      setMaskType(__in, __typeMapper);
      setName(__in, __typeMapper);
      setNameField(__in, __typeMapper);
      setNamePointing(__in, __typeMapper);
      setNillable(__in, __typeMapper);
      setPermissionable(__in, __typeMapper);
      setPicklistValues(__in, __typeMapper);
      setPolymorphicForeignKey(__in, __typeMapper);
      setPrecision(__in, __typeMapper);
      setReferenceTargetField(__in, __typeMapper);
      setReferenceTo(__in, __typeMapper);
      setRelationshipName(__in, __typeMapper);
      setRelationshipOrder(__in, __typeMapper);
      setRestrictedDelete(__in, __typeMapper);
      setRestrictedPicklist(__in, __typeMapper);
      setScale(__in, __typeMapper);
      setSearchPrefilterable(__in, __typeMapper);
      setSoapType(__in, __typeMapper);
      setSortable(__in, __typeMapper);
      setType(__in, __typeMapper);
      setUnique(__in, __typeMapper);
      setUpdateable(__in, __typeMapper);
      setWriteRequiresMasterRead(__in, __typeMapper);
    }

    private void toString1(StringBuilder sb) {
      toStringHelper(sb, "aggregatable", aggregatable);
      toStringHelper(sb, "aiPredictionField", aiPredictionField);
      toStringHelper(sb, "autoNumber", autoNumber);
      toStringHelper(sb, "byteLength", byteLength);
      toStringHelper(sb, "calculated", calculated);
      toStringHelper(sb, "calculatedFormula", calculatedFormula);
      toStringHelper(sb, "cascadeDelete", cascadeDelete);
      toStringHelper(sb, "caseSensitive", caseSensitive);
      toStringHelper(sb, "compoundFieldName", compoundFieldName);
      toStringHelper(sb, "controllerName", controllerName);
      toStringHelper(sb, "createable", createable);
      toStringHelper(sb, "custom", custom);
      toStringHelper(sb, "defaultValue", defaultValue);
      toStringHelper(sb, "defaultValueFormula", defaultValueFormula);
      toStringHelper(sb, "defaultedOnCreate", defaultedOnCreate);
      toStringHelper(sb, "dependentPicklist", dependentPicklist);
      toStringHelper(sb, "deprecatedAndHidden", deprecatedAndHidden);
      toStringHelper(sb, "digits", digits);
      toStringHelper(sb, "displayLocationInDecimal", displayLocationInDecimal);
      toStringHelper(sb, "encrypted", encrypted);
      toStringHelper(sb, "externalId", externalId);
      toStringHelper(sb, "extraTypeInfo", extraTypeInfo);
      toStringHelper(sb, "filterable", filterable);
      toStringHelper(sb, "filteredLookupInfo", filteredLookupInfo);
      toStringHelper(sb, "formulaTreatNullNumberAsZero", formulaTreatNullNumberAsZero);
      toStringHelper(sb, "groupable", groupable);
      toStringHelper(sb, "highScaleNumber", highScaleNumber);
      toStringHelper(sb, "htmlFormatted", htmlFormatted);
      toStringHelper(sb, "idLookup", idLookup);
      toStringHelper(sb, "inlineHelpText", inlineHelpText);
      toStringHelper(sb, "label", label);
      toStringHelper(sb, "length", length);
      toStringHelper(sb, "mask", mask);
      toStringHelper(sb, "maskType", maskType);
      toStringHelper(sb, "name", name);
      toStringHelper(sb, "nameField", nameField);
      toStringHelper(sb, "namePointing", namePointing);
      toStringHelper(sb, "nillable", nillable);
      toStringHelper(sb, "permissionable", permissionable);
      toStringHelper(sb, "picklistValues", picklistValues);
      toStringHelper(sb, "polymorphicForeignKey", polymorphicForeignKey);
      toStringHelper(sb, "precision", precision);
      toStringHelper(sb, "referenceTargetField", referenceTargetField);
      toStringHelper(sb, "referenceTo", referenceTo);
      toStringHelper(sb, "relationshipName", relationshipName);
      toStringHelper(sb, "relationshipOrder", relationshipOrder);
      toStringHelper(sb, "restrictedDelete", restrictedDelete);
      toStringHelper(sb, "restrictedPicklist", restrictedPicklist);
      toStringHelper(sb, "scale", scale);
      toStringHelper(sb, "searchPrefilterable", searchPrefilterable);
      toStringHelper(sb, "soapType", soapType);
      toStringHelper(sb, "sortable", sortable);
      toStringHelper(sb, "type", type);
      toStringHelper(sb, "unique", unique);
      toStringHelper(sb, "updateable", updateable);
      toStringHelper(sb, "writeRequiresMasterRead", writeRequiresMasterRead);
    }


}
