package com.sforce.soap.tooling;

import java.util.EnumSet;
import java.util.HashMap;
import java.util.Map;

/**
 * This is a generated class for the SObject Enterprise API.
 * Do not edit this file, as your changes will be lost.
 */
public enum ManageableState {


  
	/**
	 * Enumeration  : released
	 */
	released("released"),

  
	/**
	 * Enumeration  : deleted
	 */
	deleted("deleted"),

  
	/**
	 * Enumeration  : deprecated
	 */
	deprecated("deprecated"),

  
	/**
	 * Enumeration  : installed
	 */
	installed("installed"),

  
	/**
	 * Enumeration  : beta
	 */
	beta("beta"),

  
	/**
	 * Enumeration  : unmanaged
	 */
	unmanaged("unmanaged"),

;

	public static Map<String, String> valuesToEnums;

	static {
   		valuesToEnums = new HashMap<String, String>();
   		for (ManageableState e : EnumSet.allOf(ManageableState.class)) {
   			valuesToEnums.put(e.toString(), e.name());
   		}
   	}

   	private String value;

   	private ManageableState(String value) {
   		this.value = value;
   	}

   	@Override
   	public String toString() {
   		return value;
   	}
}
