package com.sforce.soap.tooling.metadata;

/**
 * This is a generated class for the SObject Enterprise API.
 * Do not edit this file, as your changes will be lost.
 */
public class CampaignInfluenceModel extends com.sforce.soap.tooling.metadata.Metadata {

    /**
     * Constructor
     */
    public CampaignInfluenceModel() {}

    /* Cache the typeInfo instead of declaring static fields throughout*/
    private transient java.util.Map<String, com.sforce.ws.bind.TypeInfo> typeInfoCache = new java.util.HashMap<String, com.sforce.ws.bind.TypeInfo>();
    private com.sforce.ws.bind.TypeInfo _lookupTypeInfo(String fieldName, String namespace, String name, String typeNS, String type, int minOcc, int maxOcc, boolean elementForm) {
      com.sforce.ws.bind.TypeInfo typeInfo = typeInfoCache.get(fieldName);
      if (typeInfo == null) {
        typeInfo = new com.sforce.ws.bind.TypeInfo(namespace, name, typeNS, type, minOcc, maxOcc, elementForm);
        typeInfoCache.put(fieldName, typeInfo);
      }
      return typeInfo;
    }

    /**
     * element : isActive of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean isActive__is_set = false;

    private boolean isActive;

    public boolean getIsActive() {
      return isActive;
    }

    public boolean isIsActive() {
      return isActive;
    }

    public void setIsActive(boolean isActive) {
      this.isActive = isActive;
      isActive__is_set = true;
    }

    protected void setIsActive(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("isActive", "urn:metadata.tooling.soap.sforce.com","isActive","http://www.w3.org/2001/XMLSchema","boolean",0,1,true))) {
        setIsActive(__typeMapper.readBoolean(__in, _lookupTypeInfo("isActive", "urn:metadata.tooling.soap.sforce.com","isActive","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), boolean.class));
      }
    }

    private void writeFieldIsActive(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("isActive", "urn:metadata.tooling.soap.sforce.com","isActive","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), isActive, isActive__is_set);
    }

    /**
     * element : isDefaultModel of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean isDefaultModel__is_set = false;

    private boolean isDefaultModel;

    public boolean getIsDefaultModel() {
      return isDefaultModel;
    }

    public boolean isIsDefaultModel() {
      return isDefaultModel;
    }

    public void setIsDefaultModel(boolean isDefaultModel) {
      this.isDefaultModel = isDefaultModel;
      isDefaultModel__is_set = true;
    }

    protected void setIsDefaultModel(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("isDefaultModel", "urn:metadata.tooling.soap.sforce.com","isDefaultModel","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setIsDefaultModel(__typeMapper.readBoolean(__in, _lookupTypeInfo("isDefaultModel", "urn:metadata.tooling.soap.sforce.com","isDefaultModel","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldIsDefaultModel(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("isDefaultModel", "urn:metadata.tooling.soap.sforce.com","isDefaultModel","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), isDefaultModel, isDefaultModel__is_set);
    }

    /**
     * element : isModelLocked of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean isModelLocked__is_set = false;

    private boolean isModelLocked;

    public boolean getIsModelLocked() {
      return isModelLocked;
    }

    public boolean isIsModelLocked() {
      return isModelLocked;
    }

    public void setIsModelLocked(boolean isModelLocked) {
      this.isModelLocked = isModelLocked;
      isModelLocked__is_set = true;
    }

    protected void setIsModelLocked(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("isModelLocked", "urn:metadata.tooling.soap.sforce.com","isModelLocked","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setIsModelLocked(__typeMapper.readBoolean(__in, _lookupTypeInfo("isModelLocked", "urn:metadata.tooling.soap.sforce.com","isModelLocked","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldIsModelLocked(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("isModelLocked", "urn:metadata.tooling.soap.sforce.com","isModelLocked","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), isModelLocked, isModelLocked__is_set);
    }

    /**
     * element : modelDescription of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean modelDescription__is_set = false;

    private java.lang.String modelDescription;

    public java.lang.String getModelDescription() {
      return modelDescription;
    }

    public void setModelDescription(java.lang.String modelDescription) {
      this.modelDescription = modelDescription;
      modelDescription__is_set = true;
    }

    protected void setModelDescription(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("modelDescription", "urn:metadata.tooling.soap.sforce.com","modelDescription","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setModelDescription(__typeMapper.readString(__in, _lookupTypeInfo("modelDescription", "urn:metadata.tooling.soap.sforce.com","modelDescription","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldModelDescription(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("modelDescription", "urn:metadata.tooling.soap.sforce.com","modelDescription","http://www.w3.org/2001/XMLSchema","string",0,1,true), modelDescription, modelDescription__is_set);
    }

    /**
     * element : name of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean name__is_set = false;

    private java.lang.String name;

    public java.lang.String getName() {
      return name;
    }

    public void setName(java.lang.String name) {
      this.name = name;
      name__is_set = true;
    }

    protected void setName(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("name", "urn:metadata.tooling.soap.sforce.com","name","http://www.w3.org/2001/XMLSchema","string",1,1,true))) {
        setName(__typeMapper.readString(__in, _lookupTypeInfo("name", "urn:metadata.tooling.soap.sforce.com","name","http://www.w3.org/2001/XMLSchema","string",1,1,true), java.lang.String.class));
      }
    }

    private void writeFieldName(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("name", "urn:metadata.tooling.soap.sforce.com","name","http://www.w3.org/2001/XMLSchema","string",1,1,true), name, name__is_set);
    }

    /**
     * element : recordPreference of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean recordPreference__is_set = false;

    private java.lang.String recordPreference;

    public java.lang.String getRecordPreference() {
      return recordPreference;
    }

    public void setRecordPreference(java.lang.String recordPreference) {
      this.recordPreference = recordPreference;
      recordPreference__is_set = true;
    }

    protected void setRecordPreference(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("recordPreference", "urn:metadata.tooling.soap.sforce.com","recordPreference","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setRecordPreference(__typeMapper.readString(__in, _lookupTypeInfo("recordPreference", "urn:metadata.tooling.soap.sforce.com","recordPreference","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldRecordPreference(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("recordPreference", "urn:metadata.tooling.soap.sforce.com","recordPreference","http://www.w3.org/2001/XMLSchema","string",0,1,true), recordPreference, recordPreference__is_set);
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      __typeMapper.writeXsiType(__out, "urn:metadata.tooling.soap.sforce.com", "CampaignInfluenceModel");
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       super.writeFields(__out, __typeMapper);
       writeFields1(__out, __typeMapper);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        super.loadFields(__in, __typeMapper);
        loadFields1(__in, __typeMapper);
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[CampaignInfluenceModel ");
      sb.append(super.toString());
      toString1(sb);

      sb.append("]\n");
      return sb.toString();
    }

    private void toStringHelper(StringBuilder sb, String name, Object value) {
      sb.append(' ').append(name).append("='").append(com.sforce.ws.util.Verbose.toString(value)).append("'\n");
    }

    private void writeFields1(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      writeFieldIsActive(__out, __typeMapper);
      writeFieldIsDefaultModel(__out, __typeMapper);
      writeFieldIsModelLocked(__out, __typeMapper);
      writeFieldModelDescription(__out, __typeMapper);
      writeFieldName(__out, __typeMapper);
      writeFieldRecordPreference(__out, __typeMapper);
    }

    private void loadFields1(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      setIsActive(__in, __typeMapper);
      setIsDefaultModel(__in, __typeMapper);
      setIsModelLocked(__in, __typeMapper);
      setModelDescription(__in, __typeMapper);
      setName(__in, __typeMapper);
      setRecordPreference(__in, __typeMapper);
    }

    private void toString1(StringBuilder sb) {
      toStringHelper(sb, "isActive", isActive);
      toStringHelper(sb, "isDefaultModel", isDefaultModel);
      toStringHelper(sb, "isModelLocked", isModelLocked);
      toStringHelper(sb, "modelDescription", modelDescription);
      toStringHelper(sb, "name", name);
      toStringHelper(sb, "recordPreference", recordPreference);
    }


}
