package com.sforce.soap.tooling.metadata;

/**
 * This is a generated class for the SObject Enterprise API.
 * Do not edit this file, as your changes will be lost.
 */
public class ContractSettings extends com.sforce.soap.tooling.metadata.MetadataForSettings {

    /**
     * Constructor
     */
    public ContractSettings() {}

    /* Cache the typeInfo instead of declaring static fields throughout*/
    private transient java.util.Map<String, com.sforce.ws.bind.TypeInfo> typeInfoCache = new java.util.HashMap<String, com.sforce.ws.bind.TypeInfo>();
    private com.sforce.ws.bind.TypeInfo _lookupTypeInfo(String fieldName, String namespace, String name, String typeNS, String type, int minOcc, int maxOcc, boolean elementForm) {
      com.sforce.ws.bind.TypeInfo typeInfo = typeInfoCache.get(fieldName);
      if (typeInfo == null) {
        typeInfo = new com.sforce.ws.bind.TypeInfo(namespace, name, typeNS, type, minOcc, maxOcc, elementForm);
        typeInfoCache.put(fieldName, typeInfo);
      }
      return typeInfo;
    }

    /**
     * element : autoCalculateEndDate of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean autoCalculateEndDate__is_set = false;

    private boolean autoCalculateEndDate;

    public boolean getAutoCalculateEndDate() {
      return autoCalculateEndDate;
    }

    public boolean isAutoCalculateEndDate() {
      return autoCalculateEndDate;
    }

    public void setAutoCalculateEndDate(boolean autoCalculateEndDate) {
      this.autoCalculateEndDate = autoCalculateEndDate;
      autoCalculateEndDate__is_set = true;
    }

    protected void setAutoCalculateEndDate(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("autoCalculateEndDate", "urn:metadata.tooling.soap.sforce.com","autoCalculateEndDate","http://www.w3.org/2001/XMLSchema","boolean",0,1,true))) {
        setAutoCalculateEndDate(__typeMapper.readBoolean(__in, _lookupTypeInfo("autoCalculateEndDate", "urn:metadata.tooling.soap.sforce.com","autoCalculateEndDate","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), boolean.class));
      }
    }

    private void writeFieldAutoCalculateEndDate(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("autoCalculateEndDate", "urn:metadata.tooling.soap.sforce.com","autoCalculateEndDate","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), autoCalculateEndDate, autoCalculateEndDate__is_set);
    }

    /**
     * element : autoExpirationDelay of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean autoExpirationDelay__is_set = false;

    private java.lang.String autoExpirationDelay;

    public java.lang.String getAutoExpirationDelay() {
      return autoExpirationDelay;
    }

    public void setAutoExpirationDelay(java.lang.String autoExpirationDelay) {
      this.autoExpirationDelay = autoExpirationDelay;
      autoExpirationDelay__is_set = true;
    }

    protected void setAutoExpirationDelay(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("autoExpirationDelay", "urn:metadata.tooling.soap.sforce.com","autoExpirationDelay","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setAutoExpirationDelay(__typeMapper.readString(__in, _lookupTypeInfo("autoExpirationDelay", "urn:metadata.tooling.soap.sforce.com","autoExpirationDelay","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldAutoExpirationDelay(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("autoExpirationDelay", "urn:metadata.tooling.soap.sforce.com","autoExpirationDelay","http://www.w3.org/2001/XMLSchema","string",0,1,true), autoExpirationDelay, autoExpirationDelay__is_set);
    }

    /**
     * element : autoExpirationRecipient of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean autoExpirationRecipient__is_set = false;

    private java.lang.String autoExpirationRecipient;

    public java.lang.String getAutoExpirationRecipient() {
      return autoExpirationRecipient;
    }

    public void setAutoExpirationRecipient(java.lang.String autoExpirationRecipient) {
      this.autoExpirationRecipient = autoExpirationRecipient;
      autoExpirationRecipient__is_set = true;
    }

    protected void setAutoExpirationRecipient(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("autoExpirationRecipient", "urn:metadata.tooling.soap.sforce.com","autoExpirationRecipient","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setAutoExpirationRecipient(__typeMapper.readString(__in, _lookupTypeInfo("autoExpirationRecipient", "urn:metadata.tooling.soap.sforce.com","autoExpirationRecipient","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldAutoExpirationRecipient(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("autoExpirationRecipient", "urn:metadata.tooling.soap.sforce.com","autoExpirationRecipient","http://www.w3.org/2001/XMLSchema","string",0,1,true), autoExpirationRecipient, autoExpirationRecipient__is_set);
    }

    /**
     * element : autoExpireContracts of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean autoExpireContracts__is_set = false;

    private boolean autoExpireContracts;

    public boolean getAutoExpireContracts() {
      return autoExpireContracts;
    }

    public boolean isAutoExpireContracts() {
      return autoExpireContracts;
    }

    public void setAutoExpireContracts(boolean autoExpireContracts) {
      this.autoExpireContracts = autoExpireContracts;
      autoExpireContracts__is_set = true;
    }

    protected void setAutoExpireContracts(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("autoExpireContracts", "urn:metadata.tooling.soap.sforce.com","autoExpireContracts","http://www.w3.org/2001/XMLSchema","boolean",0,1,true))) {
        setAutoExpireContracts(__typeMapper.readBoolean(__in, _lookupTypeInfo("autoExpireContracts", "urn:metadata.tooling.soap.sforce.com","autoExpireContracts","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), boolean.class));
      }
    }

    private void writeFieldAutoExpireContracts(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("autoExpireContracts", "urn:metadata.tooling.soap.sforce.com","autoExpireContracts","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), autoExpireContracts, autoExpireContracts__is_set);
    }

    /**
     * element : enableContractHistoryTracking of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean enableContractHistoryTracking__is_set = false;

    private boolean enableContractHistoryTracking;

    public boolean getEnableContractHistoryTracking() {
      return enableContractHistoryTracking;
    }

    public boolean isEnableContractHistoryTracking() {
      return enableContractHistoryTracking;
    }

    public void setEnableContractHistoryTracking(boolean enableContractHistoryTracking) {
      this.enableContractHistoryTracking = enableContractHistoryTracking;
      enableContractHistoryTracking__is_set = true;
    }

    protected void setEnableContractHistoryTracking(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("enableContractHistoryTracking", "urn:metadata.tooling.soap.sforce.com","enableContractHistoryTracking","http://www.w3.org/2001/XMLSchema","boolean",0,1,true))) {
        setEnableContractHistoryTracking(__typeMapper.readBoolean(__in, _lookupTypeInfo("enableContractHistoryTracking", "urn:metadata.tooling.soap.sforce.com","enableContractHistoryTracking","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), boolean.class));
      }
    }

    private void writeFieldEnableContractHistoryTracking(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("enableContractHistoryTracking", "urn:metadata.tooling.soap.sforce.com","enableContractHistoryTracking","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), enableContractHistoryTracking, enableContractHistoryTracking__is_set);
    }

    /**
     * element : notifyOwnersOnContractExpiration of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean notifyOwnersOnContractExpiration__is_set = false;

    private boolean notifyOwnersOnContractExpiration;

    public boolean getNotifyOwnersOnContractExpiration() {
      return notifyOwnersOnContractExpiration;
    }

    public boolean isNotifyOwnersOnContractExpiration() {
      return notifyOwnersOnContractExpiration;
    }

    public void setNotifyOwnersOnContractExpiration(boolean notifyOwnersOnContractExpiration) {
      this.notifyOwnersOnContractExpiration = notifyOwnersOnContractExpiration;
      notifyOwnersOnContractExpiration__is_set = true;
    }

    protected void setNotifyOwnersOnContractExpiration(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("notifyOwnersOnContractExpiration", "urn:metadata.tooling.soap.sforce.com","notifyOwnersOnContractExpiration","http://www.w3.org/2001/XMLSchema","boolean",0,1,true))) {
        setNotifyOwnersOnContractExpiration(__typeMapper.readBoolean(__in, _lookupTypeInfo("notifyOwnersOnContractExpiration", "urn:metadata.tooling.soap.sforce.com","notifyOwnersOnContractExpiration","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), boolean.class));
      }
    }

    private void writeFieldNotifyOwnersOnContractExpiration(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("notifyOwnersOnContractExpiration", "urn:metadata.tooling.soap.sforce.com","notifyOwnersOnContractExpiration","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), notifyOwnersOnContractExpiration, notifyOwnersOnContractExpiration__is_set);
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      __typeMapper.writeXsiType(__out, "urn:metadata.tooling.soap.sforce.com", "ContractSettings");
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       super.writeFields(__out, __typeMapper);
       writeFields1(__out, __typeMapper);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        super.loadFields(__in, __typeMapper);
        loadFields1(__in, __typeMapper);
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[ContractSettings ");
      sb.append(super.toString());
      toString1(sb);

      sb.append("]\n");
      return sb.toString();
    }

    private void toStringHelper(StringBuilder sb, String name, Object value) {
      sb.append(' ').append(name).append("='").append(com.sforce.ws.util.Verbose.toString(value)).append("'\n");
    }

    private void writeFields1(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      writeFieldAutoCalculateEndDate(__out, __typeMapper);
      writeFieldAutoExpirationDelay(__out, __typeMapper);
      writeFieldAutoExpirationRecipient(__out, __typeMapper);
      writeFieldAutoExpireContracts(__out, __typeMapper);
      writeFieldEnableContractHistoryTracking(__out, __typeMapper);
      writeFieldNotifyOwnersOnContractExpiration(__out, __typeMapper);
    }

    private void loadFields1(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      setAutoCalculateEndDate(__in, __typeMapper);
      setAutoExpirationDelay(__in, __typeMapper);
      setAutoExpirationRecipient(__in, __typeMapper);
      setAutoExpireContracts(__in, __typeMapper);
      setEnableContractHistoryTracking(__in, __typeMapper);
      setNotifyOwnersOnContractExpiration(__in, __typeMapper);
    }

    private void toString1(StringBuilder sb) {
      toStringHelper(sb, "autoCalculateEndDate", autoCalculateEndDate);
      toStringHelper(sb, "autoExpirationDelay", autoExpirationDelay);
      toStringHelper(sb, "autoExpirationRecipient", autoExpirationRecipient);
      toStringHelper(sb, "autoExpireContracts", autoExpireContracts);
      toStringHelper(sb, "enableContractHistoryTracking", enableContractHistoryTracking);
      toStringHelper(sb, "notifyOwnersOnContractExpiration", notifyOwnersOnContractExpiration);
    }


}
